# 🔴WAJIB RUNNING LIBRARY🔴

In [21]:
import json, re
import pandas as pd
import gspread
import os
import zipfile
import numpy as np
import getpass

from pathlib import Path
from google.auth.exceptions import GoogleAuthError
from datetime import datetime, timedelta, time
from sqlalchemy import create_engine
from sqlalchemy.exc import SQLAlchemyError
from concurrent.futures import ThreadPoolExecutor, as_completed
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build

SERVICE_ACCOUNT_FILE  = '/home/kes.ts23/infokes/iqbaalfadil/script/AKTIVASI/credential-sa-spreadsheetchecklist.json'
SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]
credentials           = Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)
gc                    = gspread.authorize(credentials)
service               = build("sheets", "v4", credentials=credentials)

# 🔴ISI DATA KONFIGURASI TERLEBIH DAHULU🔴

In [80]:
# Menentukan ID Tiket dan PIC
IDTIKET     = '#TS-2501'
# IDTIKET     = '#TS-1960'
PIC         = 'ts_iqbal_agus'
NO_MEMO     = '582/ADM-MEMO/OPR-RR/12/2025'
# NO_MEMO     = '532/ADM-MEMO/OPR-AR/11/2025'
PELANGGAN   = 'Lama'
CREATED_AT  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# 🔴TAHAP 1🔴

☑️MENGAMBIL DATA INTIME☑️

In [90]:
# Use URL ID
# revisi dengan no  memo, dan id tiket untuk append tiket ke intime di proses ketika sudah sesuai
spreadsheet_id  = '1IAR5thTwLHs42eJ28sqJMPbslhHIm8HnJqH7iTVhDmc'
sheet           = gc.open_by_key(spreadsheet_id)
worksheet       = sheet.worksheet('Detail APJ')
data            = worksheet.get_all_values()

df                = pd.DataFrame(data[1:], columns=data[0])
nama_kolom_tiket  = 'TIKET'
df_intime       = df[df[nama_kolom_tiket] == IDTIKET]
df_intime

,ID PELANGGAN,ID JEJARING,PROVINSI,NAMA KOTA/KAB,NAMA PUSKESMAS,NAMA JEJARING,JENIS FASKES,ID TIKET,STATUS,APLIKASI,LAPOR TRX,ID REVISI,REVIEW TRX,APPROVED TRX,ID AKT,NOMOR MEMO,REQ AKTIVASI,PROSES AKT,SELESAI AKT,KETERANGAN,TIKET
26,P2171010101,PU930,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Lengkang,PUSTU,,,EPUSTU,.,,4 Dec 2025 14:24:58,4 Dec 2025 14:30:58,Ae36P2171010101PU930,582/ADM-MEMO/OPR-RR/12/2025,4 Dec 25,,,,#TS-2501
27,P2171010101,PU931,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pulau Sarang,PUSTU,,,EPUSTU,.,,4 Dec 2025 14:24:58,4 Dec 2025 14:30:58,Aab6P2171010101PU931,582/ADM-MEMO/OPR-RR/12/2025,4 Dec 25,,,,#TS-2501
28,P2171010101,PU932,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Mongkol,PUSTU,,,EPUSTU,.,,4 Dec 2025 14:24:58,4 Dec 2025 14:30:58,A03eP2171010101PU932,582/ADM-MEMO/OPR-RR/12/2025,4 Dec 25,,,,#TS-2501
29,P2171010101,PU933,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pemping,PUSTU,,,EPUSTU,.,,4 Dec 2025 14:24:58,4 Dec 2025 14:30:58,A915P2171010101PU933,582/ADM-MEMO/OPR-RR/12/2025,4 Dec 25,,,,#TS-2501
30,P2171010101,PU934,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pulau Labun,PUSTU,,,EPUSTU,.,,4 Dec 2025 14:24:58,4 Dec 2025 14:30:58,A440P2171010101PU934,582/ADM-MEMO/OPR-RR/12/2025,4 Dec 25,,,,#TS-2501
31,P2171010101,PU935,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Kepala Jeri,PUSTU,,,EPUSTU,.,,4 Dec 2025 14:24:58,4 Dec 2025 14:30:58,A84cP2171010101PU935,582/ADM-MEMO/OPR-RR/12/2025,4 Dec 25,,,,#TS-2501
32,P2171010101,PU936,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Kasu 1,PUSTU,,,EPUSTU,.,,4 Dec 2025 14:24:58,4 Dec 2025 14:30:58,Af56P2171010101PU936,582/ADM-MEMO/OPR-RR/12/2025,4 Dec 25,,,,#TS-2501
33,P2171010101,PU937,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Kasu 2,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A7deP2171010101PU937,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
34,P2171010101,PU938,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Bertam,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A670P2171010101PU938,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
35,P2171010101,PU939,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pecong,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A74eP2171010101PU939,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
36,P2171010101,PU940,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pulau Terong,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A893P2171010101PU940,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
37,P2171010101,PU941,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pekasih,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A502P2171010101PU941,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
38,P2171010101,PU942,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Geranting,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Ae99P2171010101PU942,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
39,P2171020201,PU943,Kepulauan Riau,Kota Batam,Bulang,Pustu bulang lintang,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Abb9P2171020201PU943,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
40,P2171020201,PU944,Kepulauan Riau,Kota Batam,Bulang,Pustu Pulau Akar,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A950P2171020201PU944,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
41,P2171020201,PU945,Kepulauan Riau,Kota Batam,Bulang,Pustu bulang kebam,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A783P2171020201PU945,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
42,P2171020201,PU946,Kepulauan Riau,Kota Batam,Bulang,Pustu Temoyong,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A12aP2171020201PU946,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
43,P2171020201,PU947,Kepulauan Riau,Kota Batam,Bulang,Pustu pulau labu,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A407P2171020201PU947,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
44,P2171020201,PU949,Kepulauan Riau,Kota Batam,Bulang,Pustu Setokok,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Af88P2171020201PU949,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
45,P2171020201,PU948,Kepulauan Riau,Kota Batam,Bulang,Pustu Pulau air,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A8c7P2171020201PU948,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
46,P2171020201,PU950,Kepulauan Riau,Kota Batam,Bulang,Pustu selat nenek,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Ae94P2171020201PU950,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
47,P2171020201,PU951,Kepulauan Riau,Kota Batam,Bulang,Pustu panjang timur,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A16dP2171020201PU951,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
48,P2171020201,PU952,Kepulauan Riau,Kota Batam,Bulang,Pustu jaloh,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A378P2171020201PU952,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
49,P2171020201,PU953,Kepulauan Riau,Kota Batam,Bulang,Pustu cengkui,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Af8eP2171020201PU953,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
50,P2171020201,PU954,Kepulauan Riau,Kota Batam,Bulang,Pustu pulau seraya,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A2e7P2171020201PU954,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
51,P2171020201,PU955,Kepulauan Riau,Kota Batam,Bulang,Pustu Pulau Nipah,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Af72P2171020201PU955,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
52,P2171030201,PU956,Kepulauan Riau,Kota Batam,Galang,PUSTU KARAS,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A7aaP2171030201PU956,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
53,P2171030201,PU958,Kepulauan Riau,Kota Batam,Galang,POLINDES MUBUT,POLINDES,,,EPOLINDES,.,,04/12/2025,04/12/2025,A3b8P2171030201PU958,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
54,P2171030201,PU959,Kepulauan Riau,Kota Batam,Galang,PUSTU SEI RAYA,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A385P2171030201PU959,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
55,P2171030201,PU960,Kepulauan Riau,Kota Batam,Galang,PUSTU DAPUR 6,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A563P2171030201PU960,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
56,P2171030201,PU961,Kepulauan Riau,Kota Batam,Galang,PUSTU SIJANTUNG,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A7feP2171030201PU961,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
57,P2171030201,PU962,Kepulauan Riau,Kota Batam,Galang,PUSTU DAPUR 3,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Aca8P2171030201PU962,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
58,P2171030201,PU963,Kepulauan Riau,Kota Batam,Galang,PUSTU TANJUNG BANUN,PUSTU,,,EPUSTU,.,,4 Dec 2025 14:24:58,4 Dec 2025 14:30:58,A36fP2171030201PU963,582/ADM-MEMO/OPR-RR/12/2025,4 Dec 25,,,,#TS-2501
59,P2171030201,PU964,Kepulauan Riau,Kota Batam,Galang,PUSTU KOREK,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A04bP2171030201PU964,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
60,P2171030201,PU965,Kepulauan Riau,Kota Batam,Galang,PUSTU GALANG BARU,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A358P2171030201PU965,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
61,P2171030201,PU966,Kepulauan Riau,Kota Batam,Galang,PUSTU AIR LINGKA,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,AcebP2171030201PU966,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
62,P2171030201,PU967,Kepulauan Riau,Kota Batam,Galang,PUSTU PULAU PANJANG,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A1bfP2171030201PU967,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
63,P2171030201,PU968,Kepulauan Riau,Kota Batam,Galang,POLINDES PULAU PANJANG,POLINDES,,,EPOLINDES,.,,04/12/2025,04/12/2025,A8ffP2171030201PU968,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
64,P2171030201,PU969,Kepulauan Riau,Kota Batam,Galang,PUSTU PULAU NGUAN,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,AfacP2171030201PU969,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
65,P2171030201,PU970,Kepulauan Riau,Kota Batam,Galang,PUSTU SEMBUR,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Abe6P2171030201PU970,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
66,P2171030201,PU971,Kepulauan Riau,Kota Batam,Galang,POSKESDES AIR SAGA,POSKESDES,,,EPOSKESDES,.,,04/12/2025,04/12/2025,A680P2171030201PU971,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
67,P2171030201,PU972,Kepulauan Riau,Kota Batam,Galang,POLINDES PETONG,POLINDES,,,EPOLINDES,.,,04/12/2025,04/12/2025,A3e8P2171030201PU972,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
68,P2171030201,PU973,Kepulauan Riau,Kota Batam,Galang,PUSTU PULAU ABANG,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Abc8P2171030201PU973,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
69,P2171030202,PU974,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu rempang Cate,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A2c9P2171030202PU974,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
70,P2171030202,PU975,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Kampung Baru,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A3c1P2171030202PU975,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
71,P2171030202,PU976,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Air Raja,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A211P2171030202PU976,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
72,P2171030202,PU977,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Subang Mas,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A3afP2171030202PU977,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
73,P2171030202,PU978,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Tanjung Kertang,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A1d5P2171030202PU978,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
74,P2171030202,PU979,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Pasir Panjang,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Af30P2171030202PU979,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
75,P2171030202,PU980,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Monggak,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Ae40P2171030202PU980,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
76,P2171030202,PU981,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Pantai Melayu,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Af7fP2171030202PU981,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
77,P2171030202,PU982,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Tanjung Kelingking,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A9d3P2171030202PU982,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
78,P2171030202,PU983,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Belongkeng,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Ad81P2171030202PU983,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
79,P2171040101,PU984,Kepulauan Riau,Kota Batam,Sei Pancur,Pustu kampung Bagan,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A476P2171040101PU984,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
80,P2171040101,PU985,Kepulauan Riau,Kota Batam,Sei Pancur,Pustu duriangkang,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A906P2171040101PU985,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
81,P2171040101,PU986,Kepulauan Riau,Kota Batam,Sei Pancur,Pustu Pancur Baru,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Ad56P2171040101PU986,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
82,P2171040101,PU987,Kepulauan Riau,Kota Batam,Sei Pancur,pustu tanjung Piayu laut,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A523P2171040101PU987,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
83,P2171040101,PU988,Kepulauan Riau,Kota Batam,Sei Pancur,pustu bida ayu,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Afe0P2171040101PU988,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
84,P2171040101,PU989,Kepulauan Riau,Kota Batam,Sei Pancur,pustu muka kuning,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A158P2171040101PU989,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
85,P2171040101,PU990,Kepulauan Riau,Kota Batam,Sei Pancur,Pustu Mangsang,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A036P2171040101PU990,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
86,P2171050201,PU991,Kepulauan Riau,Kota Batam,Sambau,Pustu Teluk Mata Ikan,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Aae8P2171050201PU991,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
87,P2171050202,PU992,Kepulauan Riau,Kota Batam,Sei Lekop,Pustu Sei lekop,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Acc3P2171050202PU992,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
88,P2171050202,PU993,Kepulauan Riau,Kota Batam,Sei Lekop,Pustu Sei Binti,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A918P2171050202PU993,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
89,P2171050203,PU994,Kepulauan Riau,Kota Batam,Kabil,Poskesdes Kavling Senjulung,POSKESDES,,,EPOSKESDES,.,,04/12/2025,04/12/2025,AfcfP2171050203PU994,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
90,P2171050203,PU995,Kepulauan Riau,Kota Batam,Kabil,Pustu Ngenang,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A231P2171050203PU995,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
91,P2171050203,PU996,Kepulauan Riau,Kota Batam,Kabil,Pustu Kubung,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A678P2171050203PU996,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
92,P2171050203,PU997,Kepulauan Riau,Kota Batam,Kabil,Pustu Telaga Punggur,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A19aP2171050203PU997,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
93,P2171050203,PU998,Kepulauan Riau,Kota Batam,Kabil,Pustu Kampung Panau,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Adb9P2171050203PU998,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
94,P2171050204,PU999,Kepulauan Riau,Kota Batam,Kampung Jabi,Poskesdes Kampung Jabi,POSKESDES,,,EPOSKESDES,.,,04/12/2025,04/12/2025,A132P2171050204PU999,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
95,P2171050204,PU001,Kepulauan Riau,Kota Batam,Kampung Jabi,Pustu Batu Besar,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A9abP2171050204PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
96,P2171050204,PU002,Kepulauan Riau,Kota Batam,Kampung Jabi,Pustu Permata Bandara,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Ab9fP2171050204PU002,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
97,P2171051201,PU001,Kepulauan Riau,Kota Batam,Botania,Pustu Taman Raya,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,AccdP2171051201PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
98,P2171051202,PU001,Kepulauan Riau,Kota Batam,Sei Langkai,Pustu Cipta Asri,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A646P2171051202PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
99,P2171051202,PU002,Kepulauan Riau,Kota Batam,Sei Langkai,Pustu Tembesi,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Af29P2171051202PU002,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
100,P2171051202,PU003,Kepulauan Riau,Kota Batam,Sei Langkai,Pustu Tg. Gundap,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Aa1eP2171051202PU003,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
101,P2171051202,PU004,Kepulauan Riau,Kota Batam,Sei Langkai,Pustu Dapur 12,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Af34P2171051202PU004,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
102,P2171051202,PU005,Kepulauan Riau,Kota Batam,Sei Langkai,Pustu Dapur 12 pantai,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A0ebP2171051202PU005,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
103,P2171060201,PU001,Kepulauan Riau,Kota Batam,Sekupang,Pustu Tanjung Riau,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A492P2171060201PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
104,P2171060202,PU001,Kepulauan Riau,Kota Batam,Tiban Baru,PUSTU TIBA LAMA,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A7efP2171060202PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
105,P2171060203,PU001,Kepulauan Riau,Kota Batam,Mentarau,Pustu Tiban Indah,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Ae75P2171060203PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
106,P2171060203,PU002,Kepulauan Riau,Kota Batam,Mentarau,Pustu Patam Lestari,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A5e4P2171060203PU002,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
107,P2171061201,PU001,Kepulauan Riau,Kota Batam,Batu Aji,Pustu Taman Lestari,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Af85P2171061201PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
108,P2171061202,PU001,Kepulauan Riau,Kota Batam,Tanjung Uncang,PUSTU KP.CUNTING,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A7bdP2171061202PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
109,P2171061202,PU002,Kepulauan Riau,Kota Batam,Tanjung Uncang,PUSTU TELUK PANDAN,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A211P2171061202PU002,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
110,P2171070201,PU001,Kepulauan Riau,Kota Batam,Lubuk Baja,Pustu Tanjung Uma,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Aa1cP2171070201PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
111,P2171070202,PU001,Kepulauan Riau,Kota Batam,Baloi Permai,Pustu Sungai Panas,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Aed2P2171070202PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
112,P2171070202,PU002,Kepulauan Riau,Kota Batam,Baloi Permai,Pustu Taman Baloi,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Acc2P2171070202PU002,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
113,P2171081101,PU001,Kepulauan Riau,Kota Batam,Sei Panas,Pustu Bengkong Indah,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A87bP2171081101PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
114,P2171081102,PU001,Kepulauan Riau,Kota Batam,Tanjung Buntung Bengkong,Pustu Tanjung Buntung,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,Ae02P2171081102PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
115,P2171081102,PU002,Kepulauan Riau,Kota Batam,Tanjung Buntung Bengkong,Pustu Bengkong Laut,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A923P2171081102PU002,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501
116,P2171080201,PU001,Kepulauan Riau,Kota Batam,Tanjung Sengkuang,Pustu Tengki Seribu,PUSTU,,,EPUSTU,.,,04/12/2025,04/12/2025,A17aP2171080201PU001,582/ADM-MEMO/OPR-RR/12/2025,04/12/2025,,,,#TS-2501

☑️MENGAMBIL DATA MEMO GO LIVE☑️

In [94]:
# get data dengan no memo dan kolom selesai aktivasi yang kosong
spreadsheet_id  = '1IAR5thTwLHs42eJ28sqJMPbslhHIm8HnJqH7iTVhDmc'
sheet           = gc.open_by_key(spreadsheet_id)
worksheet       = sheet.worksheet('Memo Go Live')
data            = worksheet.get_all_values()

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

df_memo            = pd.DataFrame(data[1:], columns=data[0])
coloumn_memo       = 'NOMOR MEMO'
coloumn_pelanggan  = 'Jenis Pelanggan'
df_nomemo          = df_memo[df_memo[coloumn_memo] == NO_MEMO]
df_pelanggan       = df_nomemo[df_nomemo[coloumn_pelanggan] == PELANGGAN]

print('Berikut data memo go live:')
df_pelanggan

Berikut data memo go live:

,No,ID PELANGGAN,ID JEJARING,PROVINSI,NAMA KOTA/KAB,NAMA PUSKESMAS,NAMA JEJARING,JENIS FASKES,Jenis Pelanggan,NOMOR MEMO,STATUS
0,1,P2171010101,PU930,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Lengkang,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
1,2,P2171010101,PU931,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pulau Sarang,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
2,3,P2171010101,PU932,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Mongkol,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
3,4,P2171010101,PU933,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pemping,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
4,5,P2171010101,PU934,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pulau Labun,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
5,6,P2171010101,PU935,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Kepala Jeri,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
6,7,P2171010101,PU936,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Kasu 1,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
7,8,P2171010101,PU937,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Kasu 2,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
8,9,P2171010101,PU938,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Bertam,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
9,10,P2171010101,PU939,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pecong,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
10,11,P2171010101,PU940,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pulau Terong,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
11,12,P2171010101,PU941,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Pekasih,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
12,13,P2171010101,PU942,Kepulauan Riau,Kota Batam,Belakang Padang,Pustu Geranting,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
13,14,P2171020201,PU943,Kepulauan Riau,Kota Batam,Bulang,Pustu bulang lintang,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
14,15,P2171020201,PU944,Kepulauan Riau,Kota Batam,Bulang,Pustu Pulau Akar,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
15,16,P2171020201,PU945,Kepulauan Riau,Kota Batam,Bulang,Pustu bulang kebam,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
16,17,P2171020201,PU946,Kepulauan Riau,Kota Batam,Bulang,Pustu Temoyong,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
17,18,P2171020201,PU947,Kepulauan Riau,Kota Batam,Bulang,Pustu pulau labu,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
18,19,P2171020201,PU949,Kepulauan Riau,Kota Batam,Bulang,Pustu Setokok,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
19,20,P2171020201,PU948,Kepulauan Riau,Kota Batam,Bulang,Pustu Pulau air,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
20,21,P2171020201,PU950,Kepulauan Riau,Kota Batam,Bulang,Pustu selat nenek,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
21,22,P2171020201,PU951,Kepulauan Riau,Kota Batam,Bulang,Pustu panjang timur,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
22,23,P2171020201,PU952,Kepulauan Riau,Kota Batam,Bulang,Pustu jaloh,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
23,24,P2171020201,PU953,Kepulauan Riau,Kota Batam,Bulang,Pustu cengkui,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
24,25,P2171020201,PU954,Kepulauan Riau,Kota Batam,Bulang,Pustu pulau seraya,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
25,26,P2171020201,PU955,Kepulauan Riau,Kota Batam,Bulang,Pustu Pulau Nipah,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
26,27,P2171030201,PU956,Kepulauan Riau,Kota Batam,Galang,PUSTU KARAS,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
27,28,P2171030201,PU958,Kepulauan Riau,Kota Batam,Galang,POLINDES MUBUT,POLINDES,Lama,582/ADM-MEMO/OPR-RR/12/2025,
28,29,P2171030201,PU959,Kepulauan Riau,Kota Batam,Galang,PUSTU SEI RAYA,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
29,30,P2171030201,PU960,Kepulauan Riau,Kota Batam,Galang,PUSTU DAPUR 6,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
30,31,P2171030201,PU961,Kepulauan Riau,Kota Batam,Galang,PUSTU SIJANTUNG,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
31,32,P2171030201,PU962,Kepulauan Riau,Kota Batam,Galang,PUSTU DAPUR 3,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
32,33,P2171030201,PU963,Kepulauan Riau,Kota Batam,Galang,PUSTU TANJUNG BANUN,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
33,34,P2171030201,PU964,Kepulauan Riau,Kota Batam,Galang,PUSTU KOREK,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
34,35,P2171030201,PU965,Kepulauan Riau,Kota Batam,Galang,PUSTU GALANG BARU,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
35,36,P2171030201,PU966,Kepulauan Riau,Kota Batam,Galang,PUSTU AIR LINGKA,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
36,37,P2171030201,PU967,Kepulauan Riau,Kota Batam,Galang,PUSTU PULAU PANJANG,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
37,38,P2171030201,PU968,Kepulauan Riau,Kota Batam,Galang,POLINDES PULAU PANJANG,POLINDES,Lama,582/ADM-MEMO/OPR-RR/12/2025,
38,39,P2171030201,PU969,Kepulauan Riau,Kota Batam,Galang,PUSTU PULAU NGUAN,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
39,40,P2171030201,PU970,Kepulauan Riau,Kota Batam,Galang,PUSTU SEMBUR,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
40,41,P2171030201,PU971,Kepulauan Riau,Kota Batam,Galang,POSKESDES AIR SAGA,POSKESDES,Lama,582/ADM-MEMO/OPR-RR/12/2025,
41,42,P2171030201,PU972,Kepulauan Riau,Kota Batam,Galang,POLINDES PETONG,POLINDES,Lama,582/ADM-MEMO/OPR-RR/12/2025,
42,43,P2171030201,PU973,Kepulauan Riau,Kota Batam,Galang,PUSTU PULAU ABANG,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
43,44,P2171030202,PU974,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu rempang Cate,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
44,45,P2171030202,PU975,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Kampung Baru,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
45,46,P2171030202,PU976,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Air Raja,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
46,47,P2171030202,PU977,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Subang Mas,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
47,48,P2171030202,PU978,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Tanjung Kertang,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
48,49,P2171030202,PU979,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Pasir Panjang,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
49,50,P2171030202,PU980,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Monggak,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
50,51,P2171030202,PU981,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Pantai Melayu,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
51,52,P2171030202,PU982,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Tanjung Kelingking,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
52,53,P2171030202,PU983,Kepulauan Riau,Kota Batam,Rempang Cate,Pustu Belongkeng,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
53,54,P2171040101,PU984,Kepulauan Riau,Kota Batam,Sei Pancur,Pustu kampung Bagan,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
54,55,P2171040101,PU985,Kepulauan Riau,Kota Batam,Sei Pancur,Pustu duriangkang,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
55,56,P2171040101,PU986,Kepulauan Riau,Kota Batam,Sei Pancur,Pustu Pancur Baru,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
56,57,P2171040101,PU987,Kepulauan Riau,Kota Batam,Sei Pancur,pustu tanjung Piayu laut,pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
57,58,P2171040101,PU988,Kepulauan Riau,Kota Batam,Sei Pancur,pustu bida ayu,pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
58,59,P2171040101,PU989,Kepulauan Riau,Kota Batam,Sei Pancur,pustu muka kuning,pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
59,60,P2171040101,PU990,Kepulauan Riau,Kota Batam,Sei Pancur,Pustu Mangsang,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
60,61,P2171050201,PU991,Kepulauan Riau,Kota Batam,Sambau,Pustu Teluk Mata Ikan,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
61,62,P2171050202,PU992,Kepulauan Riau,Kota Batam,Sei Lekop,Pustu Sei lekop,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
62,63,P2171050202,PU993,Kepulauan Riau,Kota Batam,Sei Lekop,Pustu Sei Binti,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
63,64,P2171050203,PU994,Kepulauan Riau,Kota Batam,Kabil,Poskesdes Kavling Senjulung,Poskesdes,Lama,582/ADM-MEMO/OPR-RR/12/2025,
64,65,P2171050203,PU995,Kepulauan Riau,Kota Batam,Kabil,Pustu Ngenang,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
65,66,P2171050203,PU996,Kepulauan Riau,Kota Batam,Kabil,Pustu Kubung,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
66,67,P2171050203,PU997,Kepulauan Riau,Kota Batam,Kabil,Pustu Telaga Punggur,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
67,68,P2171050203,PU998,Kepulauan Riau,Kota Batam,Kabil,Pustu Kampung Panau,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
68,69,P2171050204,PU999,Kepulauan Riau,Kota Batam,Kampung Jabi,Poskesdes Kampung Jabi,Poskesdes,Lama,582/ADM-MEMO/OPR-RR/12/2025,
69,70,P2171050204,PU001,Kepulauan Riau,Kota Batam,Kampung Jabi,Pustu Batu Besar,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
70,71,P2171050204,PU002,Kepulauan Riau,Kota Batam,Kampung Jabi,Pustu Permata Bandara,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
71,72,P2171051201,PU001,Kepulauan Riau,Kota Batam,Botania,Pustu Taman Raya,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
72,73,P2171051202,PU001,Kepulauan Riau,Kota Batam,Sei Langkai,Pustu Cipta Asri,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
73,74,P2171051202,PU002,Kepulauan Riau,Kota Batam,Sei Langkai,Pustu Tembesi,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
74,75,P2171051202,PU003,Kepulauan Riau,Kota Batam,Sei Langkai,Pustu Tg. Gundap,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
75,76,P2171051202,PU004,Kepulauan Riau,Kota Batam,Sei Langkai,Pustu Dapur 12,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
76,77,P2171051202,PU005,Kepulauan Riau,Kota Batam,Sei Langkai,Pustu Dapur 12 pantai,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
77,78,P2171060201,PU001,Kepulauan Riau,Kota Batam,Sekupang,Pustu Tanjung Riau,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
78,79,P2171060202,PU001,Kepulauan Riau,Kota Batam,Tiban Baru,PUSTU TIBA LAMA,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
79,80,P2171060203,PU001,Kepulauan Riau,Kota Batam,Mentarau,Pustu Tiban Indah,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
80,81,P2171060203,PU002,Kepulauan Riau,Kota Batam,Mentarau,Pustu Patam Lestari,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
81,82,P2171061201,PU001,Kepulauan Riau,Kota Batam,Batu Aji,Pustu Taman Lestari,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
82,83,P2171061202,PU001,Kepulauan Riau,Kota Batam,Tanjung Uncang,PUSTU KP.CUNTING,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
83,84,P2171061202,PU002,Kepulauan Riau,Kota Batam,Tanjung Uncang,PUSTU TELUK PANDAN,PUSTU,Lama,582/ADM-MEMO/OPR-RR/12/2025,
84,85,P2171070201,PU001,Kepulauan Riau,Kota Batam,Lubuk Baja,Pustu Tanjung Uma,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
85,86,P2171070202,PU001,Kepulauan Riau,Kota Batam,Baloi Permai,Pustu Sungai Panas,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
86,87,P2171070202,PU002,Kepulauan Riau,Kota Batam,Baloi Permai,Pustu Taman Baloi,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
87,88,P2171081101,PU001,Kepulauan Riau,Kota Batam,Sei Panas,Pustu Bengkong Indah,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
88,89,P2171081102,PU001,Kepulauan Riau,Kota Batam,Tanjung Buntung Bengkong,Pustu Tanjung Buntung,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
89,90,P2171081102,PU002,Kepulauan Riau,Kota Batam,Tanjung Buntung Bengkong,Pustu Bengkong Laut,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,
90,91,P2171080201,PU001,Kepulauan Riau,Kota Batam,Tanjung Sengkuang,Pustu Tengki Seribu,Pustu,Lama,582/ADM-MEMO/OPR-RR/12/2025,

☑️COMPARE MEMO AKTIVASI DENGAN INTIME☑️

In [52]:
key_cols = [
    "ID PELANGGAN",
    "ID JEJARING",
    "PROVINSI",
    "NAMA KOTA/KAB",
    "NAMA PUSKESMAS",
    "NAMA JEJARING",
    "NOMOR MEMO"
]

In [97]:
df_nomemo_copy = df_nomemo.copy()
df_intime_copy = df_intime.copy()

# Normalisasi menjadi string
for df in [df_nomemo_copy, df_intime_copy]:
    df["ID PELANGGAN"]   = df["ID PELANGGAN"].astype(str).str.strip()
    df["ID JEJARING"]    = df["ID JEJARING"].astype(str).str.strip().str.upper()
    df["NAMA JEJARING"]  = df["NAMA JEJARING"].astype(str).str.strip()
    df["JENIS FASKES"]   = df["JENIS FASKES"].astype(str).str.strip()
    df["NAMA PUSKESMAS"] = df["NAMA PUSKESMAS"].astype(str).str.strip()
    df["PROVINSI"]       = df["PROVINSI"].astype(str).str.strip()


# REPORT 1 : SUMMARY JUMLAH DATA
print("REPORT 1 : SUMMARY TOTAL DATA")

total_memo   = len(df_nomemo_copy)
total_intime = len(df_intime_copy)

print(f"Total Data Memo   : {total_memo}")
print(f"Total Data Intime : {total_intime}")

if total_memo > total_intime:
    print(f"⚠️ WARNING: Data memo ({total_memo}) lebih banyak dari data intime ({total_intime})")
elif total_memo == total_intime:
    print(f"✅ Jumlah data memo dan intime sama ({total_memo})")
else:
    print(f"ℹ️ Data memo ({total_memo}) lebih sedikit dari data intime ({total_intime})")


# DUPLICATE MAP
def _build_dup_map(df: pd.DataFrame, subset_cols: list[str], label: str) -> dict:
    dmap    = {}
    dup_df  = df[df.duplicated(subset=subset_cols, keep=False)].copy()
    if dup_df.empty:
        return dmap

    # group key -> list sheet rows
    for _, g in dup_df.groupby(subset_cols, dropna=False):
        idxs        = g.index.tolist()
        sheet_rows  = sorted([i + 2 for i in idxs])
        rows_txt    = " dan ".join(map(str, sheet_rows)) if len(sheet_rows) == 2 else ", ".join(map(str, sheet_rows))

        msg = f"Duplikat {label}: baris no {rows_txt}"
        for i in idxs:
            dmap.setdefault(i, []).append(msg)

    return dmap

dup_map = {}
dup_a = _build_dup_map(df_nomemo_copy, ["ID PELANGGAN", "ID JEJARING"], "ID FASKES SAMA")
dup_b = _build_dup_map(df_nomemo_copy, ["NAMA JEJARING"], "NAMA JEJARING SAMA")
dup_c = _build_dup_map(df_nomemo_copy, ["ID PELANGGAN", "ID JEJARING", "NAMA JEJARING"], "ID FASKES, ID JEJARING DAN NAMA JEJARING SAMA")

# gabungkan ke satu map
for m in (dup_a, dup_b, dup_c):
    for k, v in m.items():
        dup_map.setdefault(k, []).extend(v)


# HELPER STATUS SEDERHANA
COMPARE_COLS = [
    ("ID PELANGGAN",   "id faskes beda"),
    ("ID JEJARING",    "id jejaring beda"),
    ("NAMA PUSKESMAS", "nama faskes beda"),
    ("JENIS FASKES", "jenis jejaring beda"),
    ("NAMA JEJARING",  "nama jejaring beda"),
    ("PROVINSI",       "provinsi beda"),
]

def norm(val):
    if pd.isna(val):
        return ""
    return str(val).strip().upper()


def build_status_simple(memo_row: pd.Series, intime_row: pd.Series | None) -> str:
    if intime_row is None:
        return "data tidak ada di intime"

    same_flags = []
    diffs = []

    for col, diff_label in COMPARE_COLS:
        same = (norm(memo_row[col]) == norm(intime_row[col]))
        same_flags.append(same)
        if not same:
            diffs.append(diff_label)

    if all(same_flags):
        return "sama"

    if not any(same_flags):
        return "data tidak ada di intime"

    return ", ".join(diffs)



# REPORT 2 : DETAIL PERBANDINGAN MEMO DENGAN INTIME 
print("\nREPORT 2 : DETAIL PERBANDINGAN MEMO DENGAN INTIME")

rows_output = []

for idx, row in df_nomemo_copy.iterrows():
    sheet_row = idx + 2

    # Matching baris menggunakan id pelanggan dan id jejaring
    cond = ((df_intime_copy["ID PELANGGAN"] == row["ID PELANGGAN"])
    & (df_intime_copy["ID JEJARING"] == row["ID JEJARING"]))

    intime_row = df_intime_copy.loc[cond].iloc[0] if cond.any() else None

    status_base = build_status_simple(row, intime_row)

    dup_text = " | ".join(dup_map.get(idx, []))
    final_status = status_base if not dup_text else f"{status_base} | {dup_text}"

    # Flag untuk sorting: beda/duplikat ditaruh paling atas
    is_issue = (status_base != "sama") or bool(dup_text)

    rows_output.append({
        "Row Sheet": sheet_row,

        "ID Memo": row["ID PELANGGAN"],
        "ID Intime": "" if intime_row is None else intime_row["ID PELANGGAN"],

        "ID Jejaring Memo": row["ID JEJARING"],
        "ID Jejaring Intime": "" if intime_row is None else intime_row["ID JEJARING"],

        "Nama Memo": row["NAMA PUSKESMAS"],
        "Nama Intime": "" if intime_row is None else intime_row["NAMA PUSKESMAS"],

        "Nama Jejaring Memo": row["NAMA JEJARING"],
        "Nama Jejaring Intime": "" if intime_row is None else intime_row["NAMA JEJARING"],


        "Jenis Faskes Memo": row["JENIS FASKES"],
        "Jenis Faskes Intime": "" if intime_row is None else intime_row["JENIS FASKES"],

        "Prov Memo": row["PROVINSI"],
        "Prov Intime": "" if intime_row is None else intime_row["PROVINSI"],

        "Status": final_status,
        "_is_issue": is_issue, 
    })

df_output = pd.DataFrame(rows_output)


# Fungsi shortir untuk data yang berbeda atau duplikat akan dimunculkan paling atas
df_output = (
    df_output
    .sort_values(by=["_is_issue", "Row Sheet"], ascending=[False, True])
    .drop(columns=["_is_issue"])
)

df_output

REPORT 1 : SUMMARY TOTAL DATA
Total Data Memo   : 91
Total Data Intime : 91
✅ Jumlah data memo dan intime sama (91)

REPORT 2 : DETAIL PERBANDINGAN MEMO DENGAN INTIME

,Row Sheet,ID Memo,ID Intime,ID Jejaring Memo,ID Jejaring Intime,Nama Memo,Nama Intime,Nama Jejaring Memo,Nama Jejaring Intime,Jenis Faskes Memo,Jenis Faskes Intime,Prov Memo,Prov Intime,Status
0,2,P2171010101,P2171010101,PU930,PU930,Belakang Padang,Belakang Padang,Pustu Lengkang,Pustu Lengkang,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
1,3,P2171010101,P2171010101,PU931,PU931,Belakang Padang,Belakang Padang,Pustu Pulau Sarang,Pustu Pulau Sarang,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
2,4,P2171010101,P2171010101,PU932,PU932,Belakang Padang,Belakang Padang,Pustu Mongkol,Pustu Mongkol,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
3,5,P2171010101,P2171010101,PU933,PU933,Belakang Padang,Belakang Padang,Pustu Pemping,Pustu Pemping,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
4,6,P2171010101,P2171010101,PU934,PU934,Belakang Padang,Belakang Padang,Pustu Pulau Labun,Pustu Pulau Labun,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
5,7,P2171010101,P2171010101,PU935,PU935,Belakang Padang,Belakang Padang,Pustu Kepala Jeri,Pustu Kepala Jeri,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
6,8,P2171010101,P2171010101,PU936,PU936,Belakang Padang,Belakang Padang,Pustu Kasu 1,Pustu Kasu 1,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
7,9,P2171010101,P2171010101,PU937,PU937,Belakang Padang,Belakang Padang,Pustu Kasu 2,Pustu Kasu 2,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
8,10,P2171010101,P2171010101,PU938,PU938,Belakang Padang,Belakang Padang,Pustu Bertam,Pustu Bertam,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
9,11,P2171010101,P2171010101,PU939,PU939,Belakang Padang,Belakang Padang,Pustu Pecong,Pustu Pecong,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
10,12,P2171010101,P2171010101,PU940,PU940,Belakang Padang,Belakang Padang,Pustu Pulau Terong,Pustu Pulau Terong,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
11,13,P2171010101,P2171010101,PU941,PU941,Belakang Padang,Belakang Padang,Pustu Pekasih,Pustu Pekasih,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
12,14,P2171010101,P2171010101,PU942,PU942,Belakang Padang,Belakang Padang,Pustu Geranting,Pustu Geranting,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
13,15,P2171020201,P2171020201,PU943,PU943,Bulang,Bulang,Pustu bulang lintang,Pustu bulang lintang,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
14,16,P2171020201,P2171020201,PU944,PU944,Bulang,Bulang,Pustu Pulau Akar,Pustu Pulau Akar,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
15,17,P2171020201,P2171020201,PU945,PU945,Bulang,Bulang,Pustu bulang kebam,Pustu bulang kebam,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
16,18,P2171020201,P2171020201,PU946,PU946,Bulang,Bulang,Pustu Temoyong,Pustu Temoyong,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
17,19,P2171020201,P2171020201,PU947,PU947,Bulang,Bulang,Pustu pulau labu,Pustu pulau labu,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
18,20,P2171020201,P2171020201,PU949,PU949,Bulang,Bulang,Pustu Setokok,Pustu Setokok,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
19,21,P2171020201,P2171020201,PU948,PU948,Bulang,Bulang,Pustu Pulau air,Pustu Pulau air,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
20,22,P2171020201,P2171020201,PU950,PU950,Bulang,Bulang,Pustu selat nenek,Pustu selat nenek,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
21,23,P2171020201,P2171020201,PU951,PU951,Bulang,Bulang,Pustu panjang timur,Pustu panjang timur,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
22,24,P2171020201,P2171020201,PU952,PU952,Bulang,Bulang,Pustu jaloh,Pustu jaloh,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
23,25,P2171020201,P2171020201,PU953,PU953,Bulang,Bulang,Pustu cengkui,Pustu cengkui,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
24,26,P2171020201,P2171020201,PU954,PU954,Bulang,Bulang,Pustu pulau seraya,Pustu pulau seraya,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
25,27,P2171020201,P2171020201,PU955,PU955,Bulang,Bulang,Pustu Pulau Nipah,Pustu Pulau Nipah,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
26,28,P2171030201,P2171030201,PU956,PU956,Galang,Galang,PUSTU KARAS,PUSTU KARAS,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
27,29,P2171030201,P2171030201,PU958,PU958,Galang,Galang,POLINDES MUBUT,POLINDES MUBUT,POLINDES,POLINDES,Kepulauan Riau,Kepulauan Riau,sama
28,30,P2171030201,P2171030201,PU959,PU959,Galang,Galang,PUSTU SEI RAYA,PUSTU SEI RAYA,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
29,31,P2171030201,P2171030201,PU960,PU960,Galang,Galang,PUSTU DAPUR 6,PUSTU DAPUR 6,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
30,32,P2171030201,P2171030201,PU961,PU961,Galang,Galang,PUSTU SIJANTUNG,PUSTU SIJANTUNG,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
31,33,P2171030201,P2171030201,PU962,PU962,Galang,Galang,PUSTU DAPUR 3,PUSTU DAPUR 3,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
32,34,P2171030201,P2171030201,PU963,PU963,Galang,Galang,PUSTU TANJUNG BANUN,PUSTU TANJUNG BANUN,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
33,35,P2171030201,P2171030201,PU964,PU964,Galang,Galang,PUSTU KOREK,PUSTU KOREK,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
34,36,P2171030201,P2171030201,PU965,PU965,Galang,Galang,PUSTU GALANG BARU,PUSTU GALANG BARU,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
35,37,P2171030201,P2171030201,PU966,PU966,Galang,Galang,PUSTU AIR LINGKA,PUSTU AIR LINGKA,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
36,38,P2171030201,P2171030201,PU967,PU967,Galang,Galang,PUSTU PULAU PANJANG,PUSTU PULAU PANJANG,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
37,39,P2171030201,P2171030201,PU968,PU968,Galang,Galang,POLINDES PULAU PANJANG,POLINDES PULAU PANJANG,POLINDES,POLINDES,Kepulauan Riau,Kepulauan Riau,sama
38,40,P2171030201,P2171030201,PU969,PU969,Galang,Galang,PUSTU PULAU NGUAN,PUSTU PULAU NGUAN,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
39,41,P2171030201,P2171030201,PU970,PU970,Galang,Galang,PUSTU SEMBUR,PUSTU SEMBUR,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
40,42,P2171030201,P2171030201,PU971,PU971,Galang,Galang,POSKESDES AIR SAGA,POSKESDES AIR SAGA,POSKESDES,POSKESDES,Kepulauan Riau,Kepulauan Riau,sama
41,43,P2171030201,P2171030201,PU972,PU972,Galang,Galang,POLINDES PETONG,POLINDES PETONG,POLINDES,POLINDES,Kepulauan Riau,Kepulauan Riau,sama
42,44,P2171030201,P2171030201,PU973,PU973,Galang,Galang,PUSTU PULAU ABANG,PUSTU PULAU ABANG,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
43,45,P2171030202,P2171030202,PU974,PU974,Rempang Cate,Rempang Cate,Pustu rempang Cate,Pustu rempang Cate,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
44,46,P2171030202,P2171030202,PU975,PU975,Rempang Cate,Rempang Cate,Pustu Kampung Baru,Pustu Kampung Baru,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
45,47,P2171030202,P2171030202,PU976,PU976,Rempang Cate,Rempang Cate,Pustu Air Raja,Pustu Air Raja,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
46,48,P2171030202,P2171030202,PU977,PU977,Rempang Cate,Rempang Cate,Pustu Subang Mas,Pustu Subang Mas,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
47,49,P2171030202,P2171030202,PU978,PU978,Rempang Cate,Rempang Cate,Pustu Tanjung Kertang,Pustu Tanjung Kertang,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
48,50,P2171030202,P2171030202,PU979,PU979,Rempang Cate,Rempang Cate,Pustu Pasir Panjang,Pustu Pasir Panjang,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
49,51,P2171030202,P2171030202,PU980,PU980,Rempang Cate,Rempang Cate,Pustu Monggak,Pustu Monggak,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
50,52,P2171030202,P2171030202,PU981,PU981,Rempang Cate,Rempang Cate,Pustu Pantai Melayu,Pustu Pantai Melayu,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
51,53,P2171030202,P2171030202,PU982,PU982,Rempang Cate,Rempang Cate,Pustu Tanjung Kelingking,Pustu Tanjung Kelingking,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
52,54,P2171030202,P2171030202,PU983,PU983,Rempang Cate,Rempang Cate,Pustu Belongkeng,Pustu Belongkeng,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
53,55,P2171040101,P2171040101,PU984,PU984,Sei Pancur,Sei Pancur,Pustu kampung Bagan,Pustu kampung Bagan,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
54,56,P2171040101,P2171040101,PU985,PU985,Sei Pancur,Sei Pancur,Pustu duriangkang,Pustu duriangkang,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
55,57,P2171040101,P2171040101,PU986,PU986,Sei Pancur,Sei Pancur,Pustu Pancur Baru,Pustu Pancur Baru,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
56,58,P2171040101,P2171040101,PU987,PU987,Sei Pancur,Sei Pancur,pustu tanjung Piayu laut,pustu tanjung Piayu laut,pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
57,59,P2171040101,P2171040101,PU988,PU988,Sei Pancur,Sei Pancur,pustu bida ayu,pustu bida ayu,pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
58,60,P2171040101,P2171040101,PU989,PU989,Sei Pancur,Sei Pancur,pustu muka kuning,pustu muka kuning,pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
59,61,P2171040101,P2171040101,PU990,PU990,Sei Pancur,Sei Pancur,Pustu Mangsang,Pustu Mangsang,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
60,62,P2171050201,P2171050201,PU991,PU991,Sambau,Sambau,Pustu Teluk Mata Ikan,Pustu Teluk Mata Ikan,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
61,63,P2171050202,P2171050202,PU992,PU992,Sei Lekop,Sei Lekop,Pustu Sei lekop,Pustu Sei lekop,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
62,64,P2171050202,P2171050202,PU993,PU993,Sei Lekop,Sei Lekop,Pustu Sei Binti,Pustu Sei Binti,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
63,65,P2171050203,P2171050203,PU994,PU994,Kabil,Kabil,Poskesdes Kavling Senjulung,Poskesdes Kavling Senjulung,Poskesdes,POSKESDES,Kepulauan Riau,Kepulauan Riau,sama
64,66,P2171050203,P2171050203,PU995,PU995,Kabil,Kabil,Pustu Ngenang,Pustu Ngenang,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
65,67,P2171050203,P2171050203,PU996,PU996,Kabil,Kabil,Pustu Kubung,Pustu Kubung,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
66,68,P2171050203,P2171050203,PU997,PU997,Kabil,Kabil,Pustu Telaga Punggur,Pustu Telaga Punggur,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
67,69,P2171050203,P2171050203,PU998,PU998,Kabil,Kabil,Pustu Kampung Panau,Pustu Kampung Panau,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
68,70,P2171050204,P2171050204,PU999,PU999,Kampung Jabi,Kampung Jabi,Poskesdes Kampung Jabi,Poskesdes Kampung Jabi,Poskesdes,POSKESDES,Kepulauan Riau,Kepulauan Riau,sama
69,71,P2171050204,P2171050204,PU001,PU001,Kampung Jabi,Kampung Jabi,Pustu Batu Besar,Pustu Batu Besar,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
70,72,P2171050204,P2171050204,PU002,PU002,Kampung Jabi,Kampung Jabi,Pustu Permata Bandara,Pustu Permata Bandara,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
71,73,P2171051201,P2171051201,PU001,PU001,Botania,Botania,Pustu Taman Raya,Pustu Taman Raya,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
72,74,P2171051202,P2171051202,PU001,PU001,Sei Langkai,Sei Langkai,Pustu Cipta Asri,Pustu Cipta Asri,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
73,75,P2171051202,P2171051202,PU002,PU002,Sei Langkai,Sei Langkai,Pustu Tembesi,Pustu Tembesi,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
74,76,P2171051202,P2171051202,PU003,PU003,Sei Langkai,Sei Langkai,Pustu Tg. Gundap,Pustu Tg. Gundap,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
75,77,P2171051202,P2171051202,PU004,PU004,Sei Langkai,Sei Langkai,Pustu Dapur 12,Pustu Dapur 12,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
76,78,P2171051202,P2171051202,PU005,PU005,Sei Langkai,Sei Langkai,Pustu Dapur 12 pantai,Pustu Dapur 12 pantai,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
77,79,P2171060201,P2171060201,PU001,PU001,Sekupang,Sekupang,Pustu Tanjung Riau,Pustu Tanjung Riau,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
78,80,P2171060202,P2171060202,PU001,PU001,Tiban Baru,Tiban Baru,PUSTU TIBA LAMA,PUSTU TIBA LAMA,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
79,81,P2171060203,P2171060203,PU001,PU001,Mentarau,Mentarau,Pustu Tiban Indah,Pustu Tiban Indah,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
80,82,P2171060203,P2171060203,PU002,PU002,Mentarau,Mentarau,Pustu Patam Lestari,Pustu Patam Lestari,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
81,83,P2171061201,P2171061201,PU001,PU001,Batu Aji,Batu Aji,Pustu Taman Lestari,Pustu Taman Lestari,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
82,84,P2171061202,P2171061202,PU001,PU001,Tanjung Uncang,Tanjung Uncang,PUSTU KP.CUNTING,PUSTU KP.CUNTING,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
83,85,P2171061202,P2171061202,PU002,PU002,Tanjung Uncang,Tanjung Uncang,PUSTU TELUK PANDAN,PUSTU TELUK PANDAN,PUSTU,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
84,86,P2171070201,P2171070201,PU001,PU001,Lubuk Baja,Lubuk Baja,Pustu Tanjung Uma,Pustu Tanjung Uma,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
85,87,P2171070202,P2171070202,PU001,PU001,Baloi Permai,Baloi Permai,Pustu Sungai Panas,Pustu Sungai Panas,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
86,88,P2171070202,P2171070202,PU002,PU002,Baloi Permai,Baloi Permai,Pustu Taman Baloi,Pustu Taman Baloi,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
87,89,P2171081101,P2171081101,PU001,PU001,Sei Panas,Sei Panas,Pustu Bengkong Indah,Pustu Bengkong Indah,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
88,90,P2171081102,P2171081102,PU001,PU001,Tanjung Buntung Bengkong,Tanjung Buntung Bengkong,Pustu Tanjung Buntung,Pustu Tanjung Buntung,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
89,91,P2171081102,P2171081102,PU002,PU002,Tanjung Buntung Bengkong,Tanjung Buntung Bengkong,Pustu Bengkong Laut,Pustu Bengkong Laut,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama
90,92,P2171080201,P2171080201,PU001,PU001,Tanjung Sengkuang,Tanjung Sengkuang,Pustu Tengki Seribu,Pustu Tengki Seribu,Pustu,PUSTU,Kepulauan Riau,Kepulauan Riau,sama

# CHECK DATABASE

In [98]:
# Use URL ID
spreadsheet_server  = '15IMGFofJTm9o1r-yiDRh5i9tC8M4G1qH89szm0cCEUM'
sheet               = gc.open_by_key(spreadsheet_server)
worksheet           = sheet.worksheet("Server ePuskesmas")
data_server         = worksheet.get_all_values()

df_sheet_server = pd.DataFrame(data_server[1:], columns=data_server[0])

df_lookup_server = df_intime.merge(
    df_sheet_server.rename(columns={"puskesmas_id": "ID PELANGGAN"}),
    on="ID PELANGGAN",
    how="left"
)

df_clean_server = df_lookup_server.iloc[:, [0, 1, 2, 3, 4,  5, 6, 22, 23, 24]].copy()
df_clean_server.iloc[:, 5] = df_clean_server.iloc[:, 5].astype(str).str.replace(r'^(pustu|polindes|poskesdes|posyandu|kec)\s+', '', regex=True, flags=re.IGNORECASE).str.strip().str.upper()
df_clean_server.iloc[:, 7] = df_clean_server.iloc[:, 7].str.replace(r'_[^_]+$', '', regex=True)
df_clean_server
# df_lookup_server

,ID PELANGGAN,ID JEJARING,PROVINSI,NAMA KOTA/KAB,NAMA PUSKESMAS,NAMA JEJARING,JENIS FASKES,Database,server,host
0,P2171010101,PU930,Kepulauan Riau,Kota Batam,Belakang Padang,LENGKANG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
1,P2171010101,PU931,Kepulauan Riau,Kota Batam,Belakang Padang,PULAU SARANG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
2,P2171010101,PU932,Kepulauan Riau,Kota Batam,Belakang Padang,MONGKOL,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
3,P2171010101,PU933,Kepulauan Riau,Kota Batam,Belakang Padang,PEMPING,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
4,P2171010101,PU934,Kepulauan Riau,Kota Batam,Belakang Padang,PULAU LABUN,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
5,P2171010101,PU935,Kepulauan Riau,Kota Batam,Belakang Padang,KEPALA JERI,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
6,P2171010101,PU936,Kepulauan Riau,Kota Batam,Belakang Padang,KASU 1,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
7,P2171010101,PU937,Kepulauan Riau,Kota Batam,Belakang Padang,KASU 2,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
8,P2171010101,PU938,Kepulauan Riau,Kota Batam,Belakang Padang,BERTAM,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
9,P2171010101,PU939,Kepulauan Riau,Kota Batam,Belakang Padang,PECONG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
10,P2171010101,PU940,Kepulauan Riau,Kota Batam,Belakang Padang,PULAU TERONG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
11,P2171010101,PU941,Kepulauan Riau,Kota Batam,Belakang Padang,PEKASIH,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
12,P2171010101,PU942,Kepulauan Riau,Kota Batam,Belakang Padang,GERANTING,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
13,P2171020201,PU943,Kepulauan Riau,Kota Batam,Bulang,BULANG LINTANG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
14,P2171020201,PU944,Kepulauan Riau,Kota Batam,Bulang,PULAU AKAR,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
15,P2171020201,PU945,Kepulauan Riau,Kota Batam,Bulang,BULANG KEBAM,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
16,P2171020201,PU946,Kepulauan Riau,Kota Batam,Bulang,TEMOYONG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
17,P2171020201,PU947,Kepulauan Riau,Kota Batam,Bulang,PULAU LABU,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
18,P2171020201,PU949,Kepulauan Riau,Kota Batam,Bulang,SETOKOK,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
19,P2171020201,PU948,Kepulauan Riau,Kota Batam,Bulang,PULAU AIR,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
20,P2171020201,PU950,Kepulauan Riau,Kota Batam,Bulang,SELAT NENEK,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
21,P2171020201,PU951,Kepulauan Riau,Kota Batam,Bulang,PANJANG TIMUR,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
22,P2171020201,PU952,Kepulauan Riau,Kota Batam,Bulang,JALOH,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
23,P2171020201,PU953,Kepulauan Riau,Kota Batam,Bulang,CENGKUI,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
24,P2171020201,PU954,Kepulauan Riau,Kota Batam,Bulang,PULAU SERAYA,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
25,P2171020201,PU955,Kepulauan Riau,Kota Batam,Bulang,PULAU NIPAH,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
26,P2171030201,PU956,Kepulauan Riau,Kota Batam,Galang,KARAS,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
27,P2171030201,PU958,Kepulauan Riau,Kota Batam,Galang,MUBUT,POLINDES,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
28,P2171030201,PU959,Kepulauan Riau,Kota Batam,Galang,SEI RAYA,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
29,P2171030201,PU960,Kepulauan Riau,Kota Batam,Galang,DAPUR 6,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
30,P2171030201,PU961,Kepulauan Riau,Kota Batam,Galang,SIJANTUNG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
31,P2171030201,PU962,Kepulauan Riau,Kota Batam,Galang,DAPUR 3,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
32,P2171030201,PU963,Kepulauan Riau,Kota Batam,Galang,TANJUNG BANUN,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
33,P2171030201,PU964,Kepulauan Riau,Kota Batam,Galang,KOREK,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
34,P2171030201,PU965,Kepulauan Riau,Kota Batam,Galang,GALANG BARU,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
35,P2171030201,PU966,Kepulauan Riau,Kota Batam,Galang,AIR LINGKA,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
36,P2171030201,PU967,Kepulauan Riau,Kota Batam,Galang,PULAU PANJANG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
37,P2171030201,PU968,Kepulauan Riau,Kota Batam,Galang,PULAU PANJANG,POLINDES,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
38,P2171030201,PU969,Kepulauan Riau,Kota Batam,Galang,PULAU NGUAN,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
39,P2171030201,PU970,Kepulauan Riau,Kota Batam,Galang,SEMBUR,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
40,P2171030201,PU971,Kepulauan Riau,Kota Batam,Galang,AIR SAGA,POSKESDES,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
41,P2171030201,PU972,Kepulauan Riau,Kota Batam,Galang,PETONG,POLINDES,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
42,P2171030201,PU973,Kepulauan Riau,Kota Batam,Galang,PULAU ABANG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
43,P2171030202,PU974,Kepulauan Riau,Kota Batam,Rempang Cate,REMPANG CATE,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
44,P2171030202,PU975,Kepulauan Riau,Kota Batam,Rempang Cate,KAMPUNG BARU,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
45,P2171030202,PU976,Kepulauan Riau,Kota Batam,Rempang Cate,AIR RAJA,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
46,P2171030202,PU977,Kepulauan Riau,Kota Batam,Rempang Cate,SUBANG MAS,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
47,P2171030202,PU978,Kepulauan Riau,Kota Batam,Rempang Cate,TANJUNG KERTANG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
48,P2171030202,PU979,Kepulauan Riau,Kota Batam,Rempang Cate,PASIR PANJANG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
49,P2171030202,PU980,Kepulauan Riau,Kota Batam,Rempang Cate,MONGGAK,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
50,P2171030202,PU981,Kepulauan Riau,Kota Batam,Rempang Cate,PANTAI MELAYU,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
51,P2171030202,PU982,Kepulauan Riau,Kota Batam,Rempang Cate,TANJUNG KELINGKING,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
52,P2171030202,PU983,Kepulauan Riau,Kota Batam,Rempang Cate,BELONGKENG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
53,P2171040101,PU984,Kepulauan Riau,Kota Batam,Sei Pancur,KAMPUNG BAGAN,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
54,P2171040101,PU985,Kepulauan Riau,Kota Batam,Sei Pancur,DURIANGKANG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
55,P2171040101,PU986,Kepulauan Riau,Kota Batam,Sei Pancur,PANCUR BARU,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
56,P2171040101,PU987,Kepulauan Riau,Kota Batam,Sei Pancur,TANJUNG PIAYU LAUT,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
57,P2171040101,PU988,Kepulauan Riau,Kota Batam,Sei Pancur,BIDA AYU,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
58,P2171040101,PU989,Kepulauan Riau,Kota Batam,Sei Pancur,MUKA KUNING,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
59,P2171040101,PU990,Kepulauan Riau,Kota Batam,Sei Pancur,MANGSANG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
60,P2171050201,PU991,Kepulauan Riau,Kota Batam,Sambau,TELUK MATA IKAN,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
61,P2171050202,PU992,Kepulauan Riau,Kota Batam,Sei Lekop,SEI LEKOP,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
62,P2171050202,PU993,Kepulauan Riau,Kota Batam,Sei Lekop,SEI BINTI,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
63,P2171050203,PU994,Kepulauan Riau,Kota Batam,Kabil,KAVLING SENJULUNG,POSKESDES,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
64,P2171050203,PU995,Kepulauan Riau,Kota Batam,Kabil,NGENANG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
65,P2171050203,PU996,Kepulauan Riau,Kota Batam,Kabil,KUBUNG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
66,P2171050203,PU997,Kepulauan Riau,Kota Batam,Kabil,TELAGA PUNGGUR,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
67,P2171050203,PU998,Kepulauan Riau,Kota Batam,Kabil,KAMPUNG PANAU,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
68,P2171050204,PU999,Kepulauan Riau,Kota Batam,Kampung Jabi,KAMPUNG JABI,POSKESDES,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
69,P2171050204,PU001,Kepulauan Riau,Kota Batam,Kampung Jabi,BATU BESAR,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
70,P2171050204,PU002,Kepulauan Riau,Kota Batam,Kampung Jabi,PERMATA BANDARA,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
71,P2171051201,PU001,Kepulauan Riau,Kota Batam,Botania,TAMAN RAYA,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
72,P2171051202,PU001,Kepulauan Riau,Kota Batam,Sei Langkai,CIPTA ASRI,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
73,P2171051202,PU002,Kepulauan Riau,Kota Batam,Sei Langkai,TEMBESI,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
74,P2171051202,PU003,Kepulauan Riau,Kota Batam,Sei Langkai,TG. GUNDAP,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
75,P2171051202,PU004,Kepulauan Riau,Kota Batam,Sei Langkai,DAPUR 12,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
76,P2171051202,PU005,Kepulauan Riau,Kota Batam,Sei Langkai,DAPUR 12 PANTAI,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
77,P2171060201,PU001,Kepulauan Riau,Kota Batam,Sekupang,TANJUNG RIAU,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
78,P2171060202,PU001,Kepulauan Riau,Kota Batam,Tiban Baru,TIBA LAMA,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
79,P2171060203,PU001,Kepulauan Riau,Kota Batam,Mentarau,TIBAN INDAH,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
80,P2171060203,PU002,Kepulauan Riau,Kota Batam,Mentarau,PATAM LESTARI,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
81,P2171061201,PU001,Kepulauan Riau,Kota Batam,Batu Aji,TAMAN LESTARI,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
82,P2171061202,PU001,Kepulauan Riau,Kota Batam,Tanjung Uncang,KP.CUNTING,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
83,P2171061202,PU002,Kepulauan Riau,Kota Batam,Tanjung Uncang,TELUK PANDAN,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
84,P2171070201,PU001,Kepulauan Riau,Kota Batam,Lubuk Baja,TANJUNG UMA,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
85,P2171070202,PU001,Kepulauan Riau,Kota Batam,Baloi Permai,SUNGAI PANAS,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
86,P2171070202,PU002,Kepulauan Riau,Kota Batam,Baloi Permai,TAMAN BALOI,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
87,P2171081101,PU001,Kepulauan Riau,Kota Batam,Sei Panas,BENGKONG INDAH,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
88,P2171081102,PU001,Kepulauan Riau,Kota Batam,Tanjung Buntung Bengkong,TANJUNG BUNTUNG,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
89,P2171081102,PU002,Kepulauan Riau,Kota Batam,Tanjung Buntung Bengkong,BENGKONG LAUT,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118
90,P2171080201,PU001,Kepulauan Riau,Kota Batam,Tanjung Sengkuang,TENGKI SERIBU,PUSTU,epuskesmas_ng_live_kotabatam,kep-riau-21,10.0.131.118

In [99]:
df_to_konfigurasi_ts = pd.DataFrame({
    "Puskesmas ID": df_clean_server["ID PELANGGAN"],
    "Code": df_clean_server["ID PELANGGAN"] + df_clean_server["ID JEJARING"],
    "Nama Jejaring": df_clean_server["NAMA JEJARING"],
    "Jenis Jejaring": df_clean_server["JENIS FASKES"],
    "db_dinkes": df_clean_server["Database"],
    "PIC_TS": PIC,
    "Created At": CREATED_AT
})
    
# display(df_to_konfigurasi_ts)

In [100]:
# Configure db
username = "root"
password = "root"           
host     = "localhost"
database = "dummy_data"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}/{database}")

# Check connection
with engine.connect() as conn:
    print("Connected!")

Connected!

In [ ]:
# REPORT 3a : CEK PUSKESMAS

# Ambil ID Puskesmas unik
id_puskesmas_list = (
    df_to_konfigurasi_ts["Puskesmas ID"]
    .astype(str)
    .str.strip()
    .unique()
    .tolist()
)

# print(id_puskesmas_list)

id_puskesmas_sql = ",".join(f"'{x}'" for x in id_puskesmas_list)

query_puskesmas = f"""
SELECT id AS puskesmas_id
FROM m_puskesmas
WHERE id IN ({id_puskesmas_sql});
"""

df_puskesmas_db = pd.read_sql(query_puskesmas, con=engine)
puskesmas_ada   = set(df_puskesmas_db["puskesmas_id"].astype(str))

rows_3a = []

for pid in id_puskesmas_list: 
    status = (
        "OK - FASKES SUDAH ADA"
        if pid in puskesmas_ada
        else "FASKES BELUM ADA"
    )

    rows_3a.append({
        "Puskesmas ID": pid,
        "Status": status
    })

df_report_3a = pd.DataFrame(rows_3a)

print("REPORT 3a \u2014 VALIDASI FASKES (PUSKESMAS)")
display(df_report_3a)

REPORT 3a — VALIDASI FASKES (PUSKESMAS)

   Puskesmas ID            Status
0   P2171010101  FASKES BELUM ADA
1   P2171020201  FASKES BELUM ADA
2   P2171030201  FASKES BELUM ADA
3   P2171030202  FASKES BELUM ADA
4   P2171040101  FASKES BELUM ADA
5   P2171050201  FASKES BELUM ADA
6   P2171050202  FASKES BELUM ADA
7   P2171050203  FASKES BELUM ADA
8   P2171050204  FASKES BELUM ADA
9   P2171051201  FASKES BELUM ADA
10  P2171051202  FASKES BELUM ADA
11  P2171060201  FASKES BELUM ADA
12  P2171060202  FASKES BELUM ADA
13  P2171060203  FASKES BELUM ADA
14  P2171061201  FASKES BELUM ADA
15  P2171061202  FASKES BELUM ADA
16  P2171070201  FASKES BELUM ADA
17  P2171070202  FASKES BELUM ADA
18  P2171081101  FASKES BELUM ADA
19  P2171081102  FASKES BELUM ADA
20  P2171080201  FASKES BELUM ADA

In [ ]:
# REPORT 3b : CEK JEJARING 

rows_3b = []

def norm(val):
    if pd.isna(val):
        return ""
    return str(val).strip().upper()


for _, row in df_to_konfigurasi_ts.iterrows():

    id_jejaring    = norm(row["Code"])
    nama_jejaring  = norm(row["Nama Jejaring"])
    jenis_jejaring = norm(row["Jenis Jejaring"])


    # CEK ID JEJARING
    q_id = f"""
    SELECT 1 FROM m_puskesmas
    WHERE id = '{id_jejaring}'
    LIMIT 1;
    """
    id_exist = not pd.read_sql(q_id, con=engine).empty

    # CEK NAMA + JENIS JEJARING
    q_nama_jenis = f"""
    SELECT 1 FROM m_puskesmas
    WHERE UPPER(nama) = '{nama_jejaring}' AND UPPER(jenis_puskesmas) = '{jenis_jejaring}'
    LIMIT 1;
    """
    nama_jenis_exist = not pd.read_sql(q_nama_jenis, con=engine).empty

 
    # LOGIC STATUS
    if id_exist:
        status = "ID JEJARING SUDAH ADA"

    elif (not id_exist) and nama_jenis_exist:
        status = "NAMA DAN JENIS JEJARING SUDAH ADA"

    else:
        status = "OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)"

    rows_3b.append({
        "ID Jejaring"   : id_jejaring,
        "Nama Jejaring" : row["Nama Jejaring"],
        "Jenis Jejaring": row["Jenis Jejaring"],
        "Status": status
    })

df_report_3b = pd.DataFrame(rows_3b)

print("REPORT 3b \u2014 VALIDASI JEJARING")
display(df_report_3b)

REPORT 3b — VALIDASI JEJARING

,ID Jejaring,Nama Jejaring,Jenis Jejaring,Status
0,P2171010101PU930,LENGKANG,PUSTU,ID JEJARING SUDAH ADA
1,P2171010101PU931,PULAU SARANG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
2,P2171010101PU932,MONGKOL,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
3,P2171010101PU933,PEMPING,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
4,P2171010101PU934,PULAU LABUN,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
5,P2171010101PU935,KEPALA JERI,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
6,P2171010101PU936,KASU 1,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
7,P2171010101PU937,KASU 2,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
8,P2171010101PU938,BERTAM,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
9,P2171010101PU939,PECONG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
10,P2171010101PU940,PULAU TERONG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
11,P2171010101PU941,PEKASIH,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
12,P2171010101PU942,GERANTING,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
13,P2171020201PU943,BULANG LINTANG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
14,P2171020201PU944,PULAU AKAR,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
15,P2171020201PU945,BULANG KEBAM,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
16,P2171020201PU946,TEMOYONG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
17,P2171020201PU947,PULAU LABU,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
18,P2171020201PU949,SETOKOK,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
19,P2171020201PU948,PULAU AIR,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
20,P2171020201PU950,SELAT NENEK,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
21,P2171020201PU951,PANJANG TIMUR,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
22,P2171020201PU952,JALOH,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
23,P2171020201PU953,CENGKUI,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
24,P2171020201PU954,PULAU SERAYA,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
25,P2171020201PU955,PULAU NIPAH,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
26,P2171030201PU956,KARAS,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
27,P2171030201PU958,MUBUT,POLINDES,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
28,P2171030201PU959,SEI RAYA,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
29,P2171030201PU960,DAPUR 6,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
30,P2171030201PU961,SIJANTUNG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
31,P2171030201PU962,DAPUR 3,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
32,P2171030201PU963,TANJUNG BANUN,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
33,P2171030201PU964,KOREK,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
34,P2171030201PU965,GALANG BARU,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
35,P2171030201PU966,AIR LINGKA,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
36,P2171030201PU967,PULAU PANJANG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
37,P2171030201PU968,PULAU PANJANG,POLINDES,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
38,P2171030201PU969,PULAU NGUAN,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
39,P2171030201PU970,SEMBUR,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
40,P2171030201PU971,AIR SAGA,POSKESDES,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
41,P2171030201PU972,PETONG,POLINDES,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
42,P2171030201PU973,PULAU ABANG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
43,P2171030202PU974,REMPANG CATE,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
44,P2171030202PU975,KAMPUNG BARU,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
45,P2171030202PU976,AIR RAJA,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
46,P2171030202PU977,SUBANG MAS,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
47,P2171030202PU978,TANJUNG KERTANG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
48,P2171030202PU979,PASIR PANJANG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
49,P2171030202PU980,MONGGAK,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
50,P2171030202PU981,PANTAI MELAYU,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
51,P2171030202PU982,TANJUNG KELINGKING,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
52,P2171030202PU983,BELONGKENG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
53,P2171040101PU984,KAMPUNG BAGAN,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
54,P2171040101PU985,DURIANGKANG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
55,P2171040101PU986,PANCUR BARU,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
56,P2171040101PU987,TANJUNG PIAYU LAUT,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
57,P2171040101PU988,BIDA AYU,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
58,P2171040101PU989,MUKA KUNING,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
59,P2171040101PU990,MANGSANG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
60,P2171050201PU991,TELUK MATA IKAN,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
61,P2171050202PU992,SEI LEKOP,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
62,P2171050202PU993,SEI BINTI,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
63,P2171050203PU994,KAVLING SENJULUNG,POSKESDES,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
64,P2171050203PU995,NGENANG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
65,P2171050203PU996,KUBUNG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
66,P2171050203PU997,TELAGA PUNGGUR,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
67,P2171050203PU998,KAMPUNG PANAU,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
68,P2171050204PU999,KAMPUNG JABI,POSKESDES,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
69,P2171050204PU001,BATU BESAR,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
70,P2171050204PU002,PERMATA BANDARA,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
71,P2171051201PU001,TAMAN RAYA,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
72,P2171051202PU001,CIPTA ASRI,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
73,P2171051202PU002,TEMBESI,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
74,P2171051202PU003,TG. GUNDAP,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
75,P2171051202PU004,DAPUR 12,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
76,P2171051202PU005,DAPUR 12 PANTAI,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
77,P2171060201PU001,TANJUNG RIAU,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
78,P2171060202PU001,TIBA LAMA,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
79,P2171060203PU001,TIBAN INDAH,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
80,P2171060203PU002,PATAM LESTARI,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
81,P2171061201PU001,TAMAN LESTARI,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
82,P2171061202PU001,KP.CUNTING,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
83,P2171061202PU002,TELUK PANDAN,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
84,P2171070201PU001,TANJUNG UMA,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
85,P2171070202PU001,SUNGAI PANAS,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
86,P2171070202PU002,TAMAN BALOI,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
87,P2171081101PU001,BENGKONG INDAH,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
88,P2171081102PU001,TANJUNG BUNTUNG,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
89,P2171081102PU002,BENGKONG LAUT,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)
90,P2171080201PU001,TENGKI SERIBU,PUSTU,OK - JEJARING BELUM ADA (SIAP DIAKTIVASI)

In [ ]:
LOOKUP_MASTER_DB = "dummy_data"   # lokal
# LOOKUP_MASTER_DB = "epuskesmas_master"  # production

def norm(val):
    if pd.isna(val):
        return ""
    return str(val).strip().upper()

rows_report4 = []

for _, row in df_clean_server.iterrows():

    jenis_faskes = norm(row["JENIS FASKES"])
    id_jejaring  = row["ID JEJARING"]

    if jenis_faskes == "":
        rows_report4.append({
            "ID Jejaring": id_jejaring,
            "Jenis Faskes": jenis_faskes,
            "Jumlah di m_lookup": None,
            "Status": "JENIS FASKES KOSONG"
        })
        continue

    query = f"""
    SELECT COUNT(1) AS total
    FROM {LOOKUP_MASTER_DB}.m_lookup
    WHERE `for` = 'jenis_puskesmas'
      AND UPPER(`value`) = '{jenis_faskes}';
    """

    try:
        total = int(pd.read_sql(query, con=engine).iloc[0, 0])
        status = (
            "JENIS JEJARING SUDAH ADA"
            if total > 0
            else "JENIS JEJARING TIDAK ADA (PERLU INSERT)"
        )
    except Exception:
        total   = None
        status  = "ERROR LOOKUP MASTER"

    rows_report4.append({
        "ID Jejaring": id_jejaring,
        "Jenis Faskes": jenis_faskes,
        "Jumlah di m_lookup": total,
        "Status": status
    })

df_report4 = pd.DataFrame(rows_report4)

print("REPORT 4 — VALIDASI JENIS JEJARING (MASTER LOOKUP)")
display(df_report4)

REPORT 4 — VALIDASI JENIS JEJARING (MASTER LOOKUP)

,ID Jejaring,Jenis Faskes,Jumlah di m_lookup,Status
0,PU930,PUSTU,1,JENIS JEJARING SUDAH ADA
1,PU931,PUSTU,1,JENIS JEJARING SUDAH ADA
2,PU932,PUSTU,1,JENIS JEJARING SUDAH ADA
3,PU933,PUSTU,1,JENIS JEJARING SUDAH ADA
4,PU934,PUSTU,1,JENIS JEJARING SUDAH ADA
5,PU935,PUSTU,1,JENIS JEJARING SUDAH ADA
6,PU936,PUSTU,1,JENIS JEJARING SUDAH ADA
7,PU937,PUSTU,1,JENIS JEJARING SUDAH ADA
8,PU938,PUSTU,1,JENIS JEJARING SUDAH ADA
9,PU939,PUSTU,1,JENIS JEJARING SUDAH ADA
10,PU940,PUSTU,1,JENIS JEJARING SUDAH ADA
11,PU941,PUSTU,1,JENIS JEJARING SUDAH ADA
12,PU942,PUSTU,1,JENIS JEJARING SUDAH ADA
13,PU943,PUSTU,1,JENIS JEJARING SUDAH ADA
14,PU944,PUSTU,1,JENIS JEJARING SUDAH ADA
15,PU945,PUSTU,1,JENIS JEJARING SUDAH ADA
16,PU946,PUSTU,1,JENIS JEJARING SUDAH ADA
17,PU947,PUSTU,1,JENIS JEJARING SUDAH ADA
18,PU949,PUSTU,1,JENIS JEJARING SUDAH ADA
19,PU948,PUSTU,1,JENIS JEJARING SUDAH ADA
20,PU950,PUSTU,1,JENIS JEJARING SUDAH ADA
21,PU951,PUSTU,1,JENIS JEJARING SUDAH ADA
22,PU952,PUSTU,1,JENIS JEJARING SUDAH ADA
23,PU953,PUSTU,1,JENIS JEJARING SUDAH ADA
24,PU954,PUSTU,1,JENIS JEJARING SUDAH ADA
25,PU955,PUSTU,1,JENIS JEJARING SUDAH ADA
26,PU956,PUSTU,1,JENIS JEJARING SUDAH ADA
27,PU958,POLINDES,0,JENIS JEJARING TIDAK ADA (PERLU INSERT)
28,PU959,PUSTU,1,JENIS JEJARING SUDAH ADA
29,PU960,PUSTU,1,JENIS JEJARING SUDAH ADA
30,PU961,PUSTU,1,JENIS JEJARING SUDAH ADA
31,PU962,PUSTU,1,JENIS JEJARING SUDAH ADA
32,PU963,PUSTU,1,JENIS JEJARING SUDAH ADA
33,PU964,PUSTU,1,JENIS JEJARING SUDAH ADA
34,PU965,PUSTU,1,JENIS JEJARING SUDAH ADA
35,PU966,PUSTU,1,JENIS JEJARING SUDAH ADA
36,PU967,PUSTU,1,JENIS JEJARING SUDAH ADA
37,PU968,POLINDES,0,JENIS JEJARING TIDAK ADA (PERLU INSERT)
38,PU969,PUSTU,1,JENIS JEJARING SUDAH ADA
39,PU970,PUSTU,1,JENIS JEJARING SUDAH ADA
40,PU971,POSKESDES,1,JENIS JEJARING SUDAH ADA
41,PU972,POLINDES,0,JENIS JEJARING TIDAK ADA (PERLU INSERT)
42,PU973,PUSTU,1,JENIS JEJARING SUDAH ADA
43,PU974,PUSTU,1,JENIS JEJARING SUDAH ADA
44,PU975,PUSTU,1,JENIS JEJARING SUDAH ADA
45,PU976,PUSTU,1,JENIS JEJARING SUDAH ADA
46,PU977,PUSTU,1,JENIS JEJARING SUDAH ADA
47,PU978,PUSTU,1,JENIS JEJARING SUDAH ADA
48,PU979,PUSTU,1,JENIS JEJARING SUDAH ADA
49,PU980,PUSTU,1,JENIS JEJARING SUDAH ADA
50,PU981,PUSTU,1,JENIS JEJARING SUDAH ADA
51,PU982,PUSTU,1,JENIS JEJARING SUDAH ADA
52,PU983,PUSTU,1,JENIS JEJARING SUDAH ADA
53,PU984,PUSTU,1,JENIS JEJARING SUDAH ADA
54,PU985,PUSTU,1,JENIS JEJARING SUDAH ADA
55,PU986,PUSTU,1,JENIS JEJARING SUDAH ADA
56,PU987,PUSTU,1,JENIS JEJARING SUDAH ADA
57,PU988,PUSTU,1,JENIS JEJARING SUDAH ADA
58,PU989,PUSTU,1,JENIS JEJARING SUDAH ADA
59,PU990,PUSTU,1,JENIS JEJARING SUDAH ADA
60,PU991,PUSTU,1,JENIS JEJARING SUDAH ADA
61,PU992,PUSTU,1,JENIS JEJARING SUDAH ADA
62,PU993,PUSTU,1,JENIS JEJARING SUDAH ADA
63,PU994,POSKESDES,1,JENIS JEJARING SUDAH ADA
64,PU995,PUSTU,1,JENIS JEJARING SUDAH ADA
65,PU996,PUSTU,1,JENIS JEJARING SUDAH ADA
66,PU997,PUSTU,1,JENIS JEJARING SUDAH ADA
67,PU998,PUSTU,1,JENIS JEJARING SUDAH ADA
68,PU999,POSKESDES,1,JENIS JEJARING SUDAH ADA
69,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
70,PU002,PUSTU,1,JENIS JEJARING SUDAH ADA
71,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
72,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
73,PU002,PUSTU,1,JENIS JEJARING SUDAH ADA
74,PU003,PUSTU,1,JENIS JEJARING SUDAH ADA
75,PU004,PUSTU,1,JENIS JEJARING SUDAH ADA
76,PU005,PUSTU,1,JENIS JEJARING SUDAH ADA
77,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
78,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
79,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
80,PU002,PUSTU,1,JENIS JEJARING SUDAH ADA
81,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
82,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
83,PU002,PUSTU,1,JENIS JEJARING SUDAH ADA
84,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
85,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
86,PU002,PUSTU,1,JENIS JEJARING SUDAH ADA
87,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
88,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA
89,PU002,PUSTU,1,JENIS JEJARING SUDAH ADA
90,PU001,PUSTU,1,JENIS JEJARING SUDAH ADA

In [ ]:
# REPORT 4 : CEK JENIS JEJARING DI m_lookup

rows_report4 = []

for _, row in df_clean_server.iterrows():

    database     = str(row["Database"]).strip()
    jenis_faskes = norm(row["JENIS FASKES"])
    id_jejaring  = row["ID JEJARING"]


    # Validasi awal
    if database == "" or jenis_faskes == "":
        rows_report4.append({
            "Database": database,
            "ID Jejaring": id_jejaring,
            "Jenis Faskes": jenis_faskes,
            "Jumlah di m_lookup": None,
            "Status": "DATABASE / JENIS FASKES KOSONG"
        })
        continue

 
    # Query cek jenis_puskesmas
    query = f"""
    SELECT COUNT(1) AS total, '{jenis_faskes}' AS value
    FROM {database}.m_lookup
    WHERE `for` = 'jenis_puskesmas'
      AND UPPER(`value`) = '{jenis_faskes}';
    """

    try:
        df_check = pd.read_sql(query, con=engine)
        total = int(df_check.iloc[0]["total"])

        if total > 0:
            status = "JENIS JEJARING SUDAH ADA"
        else:
            status = "JENIS JEJARING TIDAK ADA (PERLU INSERT)"

    except Exception as e:
        total = None
        status = f"ERROR QUERY: {str(e)}"

    rows_report4.append({
        "Database": database,
        "ID Jejaring": id_jejaring,
        "Jenis Faskes": jenis_faskes,
        "Jumlah di m_lookup": total,
        "Status": status
    })


df_report4 = pd.DataFrame(rows_report4)
print("REPORT 4 \u2014 VALIDASI JENIS JEJARING (m_lookup)")
display(df_report4)

REPORT 4 — VALIDASI JENIS JEJARING (m_lookup)

,Database,ID Jejaring,Jenis Faskes,Jumlah di m_lookup,Status
0,epuskesmas_ng_live_kotabatam,PU930,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
1,epuskesmas_ng_live_kotabatam,PU931,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
2,epuskesmas_ng_live_kotabatam,PU932,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
3,epuskesmas_ng_live_kotabatam,PU933,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
4,epuskesmas_ng_live_kotabatam,PU934,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
5,epuskesmas_ng_live_kotabatam,PU935,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
6,epuskesmas_ng_live_kotabatam,PU936,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
7,epuskesmas_ng_live_kotabatam,PU937,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
8,epuskesmas_ng_live_kotabatam,PU938,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
9,epuskesmas_ng_live_kotabatam,PU939,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
10,epuskesmas_ng_live_kotabatam,PU940,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
11,epuskesmas_ng_live_kotabatam,PU941,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
12,epuskesmas_ng_live_kotabatam,PU942,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
13,epuskesmas_ng_live_kotabatam,PU943,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
14,epuskesmas_ng_live_kotabatam,PU944,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
15,epuskesmas_ng_live_kotabatam,PU945,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
16,epuskesmas_ng_live_kotabatam,PU946,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
17,epuskesmas_ng_live_kotabatam,PU947,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
18,epuskesmas_ng_live_kotabatam,PU949,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
19,epuskesmas_ng_live_kotabatam,PU948,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
20,epuskesmas_ng_live_kotabatam,PU950,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
21,epuskesmas_ng_live_kotabatam,PU951,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
22,epuskesmas_ng_live_kotabatam,PU952,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
23,epuskesmas_ng_live_kotabatam,PU953,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
24,epuskesmas_ng_live_kotabatam,PU954,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
25,epuskesmas_ng_live_kotabatam,PU955,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
26,epuskesmas_ng_live_kotabatam,PU956,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
27,epuskesmas_ng_live_kotabatam,PU958,POLINDES,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'POLINDES' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'POLINDES';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
28,epuskesmas_ng_live_kotabatam,PU959,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
29,epuskesmas_ng_live_kotabatam,PU960,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
30,epuskesmas_ng_live_kotabatam,PU961,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
31,epuskesmas_ng_live_kotabatam,PU962,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
32,epuskesmas_ng_live_kotabatam,PU963,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
33,epuskesmas_ng_live_kotabatam,PU964,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
34,epuskesmas_ng_live_kotabatam,PU965,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
35,epuskesmas_ng_live_kotabatam,PU966,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
36,epuskesmas_ng_live_kotabatam,PU967,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
37,epuskesmas_ng_live_kotabatam,PU968,POLINDES,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'POLINDES' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'POLINDES';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
38,epuskesmas_ng_live_kotabatam,PU969,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
39,epuskesmas_ng_live_kotabatam,PU970,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
40,epuskesmas_ng_live_kotabatam,PU971,POSKESDES,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'POSKESDES' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'POSKESDES';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
41,epuskesmas_ng_live_kotabatam,PU972,POLINDES,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'POLINDES' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'POLINDES';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
42,epuskesmas_ng_live_kotabatam,PU973,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
43,epuskesmas_ng_live_kotabatam,PU974,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
44,epuskesmas_ng_live_kotabatam,PU975,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
45,epuskesmas_ng_live_kotabatam,PU976,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
46,epuskesmas_ng_live_kotabatam,PU977,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
47,epuskesmas_ng_live_kotabatam,PU978,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
48,epuskesmas_ng_live_kotabatam,PU979,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"
49,epuskesmas_ng_live_kotabatam,PU980,PUSTU,None,"ERROR QUERY: (pymysql.err.ProgrammingError) (1146, ""Table 'epuskesmas_ng_live_kotabatam.m_lookup' doesn't exist"")\n[SQL: \n SELECT COUNT(1) AS total, 'PUSTU' AS value\n FROM epuskesmas_ng_live_kotabatam.m_lookup\n WHERE `for` = 'jenis_puskesmas'\n AND UPPER(`value`) = 'PUSTU';\n ]\n(Background on this error at: https://sqlalche.me/e/20/f405)"

In [20]:
id_list = df_to_konfigurasi_ts["Code"].astype(str).unique().tolist()
id_list_sql = ",".join(f"'{x}'" for x in id_list)

query = f"""
SELECT 
    id,
    jenis_puskesmas,
    nama,
    db_database,
    alamat,
    stok_obat_realtime,
    created_at,
    updated_at
FROM m_puskesmas
WHERE id IN ({id_list_sql});
"""

df_lookup = pd.read_sql(query, con=engine)

df_merged = df_to_konfigurasi_ts.merge(
    df_lookup,
    left_on="Code",
    right_on="id",
    how="left"
)

df_merged["Status DB"] = df_merged["id"].apply(
    lambda x: "ADA DI DATABASE" if pd.notnull(x) else "TIDAK ADA"
)

print('Berikut hasil pencocokan jejaring dengan database :')
# df_merged = df_merged.iloc[:, [1, 2, 3, 4, 7, 15]].copy()
display(df_merged)

Berikut hasil pencocokan jejaring dengan database :

,Puskesmas ID,Code,Nama Jejaring,Jenis Jejaring,db_dinkes,PIC_TS,Created At,id,jenis_puskesmas,nama,db_database,alamat,stok_obat_realtime,created_at,updated_at,Status DB
0,P7212050101,P7212050101PU001,GILILANA,PUSTU,epuskesmas_ng_live_morowaliutara,ts_iqbal_agus,2025-12-28 13:16:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA
1,P7212050101,P7212050101PU002,⁠TANAUGE,PUSTU,epuskesmas_ng_live_morowaliutara,ts_iqbal_agus,2025-12-28 13:16:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA
2,P7212050101,P7212050101PU003,GANDA GANDA,POSKESDES,epuskesmas_ng_live_morowaliutara,ts_iqbal_agus,2025-12-28 13:16:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA
3,P7212050101,P7212050101PU004,KOROMATANTU,POSKESDES,epuskesmas_ng_live_morowaliutara,ts_iqbal_agus,2025-12-28 13:16:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA
4,P7212050101,P7212050101PU005,⁠KOROLOLAKI,POSKESDES,epuskesmas_ng_live_morowaliutara,ts_iqbal_agus,2025-12-28 13:16:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA
5,P7212050101,P7212050101PU006,KOYA,POSKESDES,epuskesmas_ng_live_morowaliutara,ts_iqbal_agus,2025-12-28 13:16:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA
6,P7212050101,P7212050101PU007,KOROLOLAMA,POSKESDES,epuskesmas_ng_live_morowaliutara,ts_iqbal_agus,2025-12-28 13:16:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA
7,P7212050101,P7212050101PU008,BAHONTULA,POSKESDES,epuskesmas_ng_live_morowaliutara,ts_iqbal_agus,2025-12-28 13:16:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA
8,P7212050101,P7212050101PU009,BAHOUE,POSKESDES,epuskesmas_ng_live_morowaliutara,ts_iqbal_agus,2025-12-28 13:16:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA
9,P7212050101,P7212050101PU010,KOLONODALE,POSKESDES,epuskesmas_ng_live_morowaliutara,ts_iqbal_agus,2025-12-28 13:16:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA
10,P7212050101,P7212050101PU011,LAMBOLO,POSKESDES,epuskesmas_ng_live_morowaliutara,ts_iqbal_agus,2025-12-28 13:16:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TIDAK ADA

In [ ]:
# ======================================================
# REPORT 3 (SUPSERSET)
# 3a: VALIDASI ID PELANGGAN (WAJIB SUDAH ADA)
# 3b: VALIDASI ID JEJARING (WAJIB BELUM ADA)
# ======================================================

import pandas as pd

rows_report3 = []

# ======================================================
# STEP 1 — LOOKUP ID PELANGGAN (SUPSERSET DB)
# ======================================================

id_pelanggan_list = (df_to_konfigurasi_ts["Puskesmas ID"].astype(str).str.strip().unique().tolist())

id_pelanggan_sql = ",".join(f"'{x}'" for x in id_pelanggan_list)

query_pelanggan = f"""
SELECT id
FROM m_puskesmas
WHERE id IN ({id_pelanggan_sql});
"""

df_pelanggan_db = pd.read_sql(query_pelanggan, con=engine)
id_pelanggan_ada = set(df_pelanggan_db["id"].astype(str))

# ======================================================
# STEP 2 — LOOP REPORT 3
# ======================================================
for _, row in df_to_konfigurasi_ts.iterrows():

    id_pelanggan   = str(row["Puskesmas ID"]).strip()
    id_jejaring    = str(row["Code"]).strip()   # atau kolom ID JEJARING
    nama_jejaring  = row["Nama Jejaring"]
    jenis_jejaring = row["Jenis Jejaring"]

    # --------------------------------------------------
    # REPORT 3a — CEK ID PELANGGAN
    # --------------------------------------------------
    if id_pelanggan not in id_pelanggan_ada:
        status = "ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)"

    else:
        # --------------------------------------------------
        # REPORT 3b — CEK ID JEJARING
        # --------------------------------------------------
        query_jejaring = f"""
        SELECT id
        FROM m_puskesmas
        WHERE id = '{id_jejaring}';
        """
        df_jejaring_db = pd.read_sql(query_jejaring, con=engine)

        if not df_jejaring_db.empty:
            status = "ERROR 3B: ID JEJARING SUDAH ADA (AKUN SUDAH DIBUAT)"
        else:
            status = "OK: SIAP AKTIVASI AKUN JEJARING"

    rows_report3.append({
        "ID PELANGGAN": id_pelanggan,
        "ID JEJARING": id_jejaring,
        "NAMA JEJARING": nama_jejaring,
        "JENIS JEJARING": jenis_jejaring,
        "STATUS": status
    })

# ======================================================
# OUTPUT REPORT 3
# ======================================================
df_report3 = pd.DataFrame(rows_report3)

print("REPORT 3 (SUPSERSET) — VALIDASI AKUN JEJARING")
display(df_report3)

REPORT 3 (SUPSERSET) — VALIDASI AKUN JEJARING

,ID PELANGGAN,ID JEJARING,NAMA JEJARING,JENIS JEJARING,STATUS
0,P7212050101,P7212050101PU001,GILILANA,PUSTU,ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)
1,P7212050101,P7212050101PU002,⁠TANAUGE,PUSTU,ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)
2,P7212050101,P7212050101PU003,GANDA GANDA,POSKESDES,ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)
3,P7212050101,P7212050101PU004,KOROMATANTU,POSKESDES,ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)
4,P7212050101,P7212050101PU005,⁠KOROLOLAKI,POSKESDES,ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)
5,P7212050101,P7212050101PU006,KOYA,POSKESDES,ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)
6,P7212050101,P7212050101PU007,KOROLOLAMA,POSKESDES,ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)
7,P7212050101,P7212050101PU008,BAHONTULA,POSKESDES,ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)
8,P7212050101,P7212050101PU009,BAHOUE,POSKESDES,ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)
9,P7212050101,P7212050101PU010,KOLONODALE,POSKESDES,ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)
10,P7212050101,P7212050101PU011,LAMBOLO,POSKESDES,ERROR 3A: ID PELANGGAN BELUM ADA (AKUN INDUK BELUM DIBUAT)

☑️MENYALIN DAN MELENGKAPI INFORMASI JEJARING DARI INTIME KE KONFIGURASI TS☑️

In [52]:
SPREADSHEET_KONFIGURASI_TS  = '1IAR5thTwLHs42eJ28sqJMPbslhHIm8HnJqH7iTVhDmc'
SHEET_NAME_TARGET           = "Jejaring"

# Get the number of filled rows in the sheet
sheet_metadata = service.spreadsheets().get(spreadsheetId=SPREADSHEET_KONFIGURASI_TS).execute()
sheet_props = next(
    (s for s in sheet_metadata.get("sheets", []) if s["properties"]["title"] == SHEET_NAME_TARGET),
    None
)

if sheet_props:
    grid_props = sheet_props["properties"]["gridProperties"]
    read_range = f"{SHEET_NAME_TARGET}!A:A"
    result = service.spreadsheets().values().get(
        spreadsheetId=SPREADSHEET_KONFIGURASI_TS, range=read_range
    ).execute()
    existing_rows = len(result.get("values", []))
else:
    raise Exception(f"Sheet '{SHEET_NAME_TARGET}' tidak ditemukan.")

# Specify the starting line for appending
start_row = existing_rows + 1
range_append = f"{SHEET_NAME_TARGET}!A{start_row}"
end_row = start_row + len(df_to_konfigurasi_ts) - 1
values = df_to_konfigurasi_ts.values.tolist()
# Append data
service.spreadsheets().values().append(
    spreadsheetId=SPREADSHEET_KONFIGURASI_TS,
    range=range_append,
    valueInputOption="RAW",
    insertDataOption="INSERT_ROWS",
    body={"values": values}
).execute()

print(f"{len(values)} baris telah ditambahkan dari baris {start_row} sampai baris {end_row}.")

11 baris telah ditambahkan dari baris 14 sampai baris 24.

In [ ]:
# ==============================================================================================================================================================================================================

In [ ]:
# # cleansing data from sheet Detail APJ for sheet Jejaring
df_selected         = df_lookup_server.iloc[:, [0, 1, 5, 6, 2, 3]]
df_selected.columns = ['ID PELANGGAN', 'ID JEJARING','NAMA JEJARING', 'JENIS FASKES', 'PROVINSI', 'NAMA KOTA/KAB']
df_selected['NAMA JEJARING']  = (df_selected['NAMA JEJARING'].astype(str).str.replace(r'^(pustu|polindes|poskesdes|posyandu|kec)\s+', '', regex=True, flags=re.IGNORECASE).str.strip().str.upper())
df_selected['NAMA SERVER']    = ('epuskesmas_ng_live_' + df_selected['NAMA KOTA/KAB'].astype(str).str.lower().str.replace(r'\b(kabupaten|kab|kota)\b', '', regex=True).str.replace(r'[^a-z0-9]', '', regex=True))
df_selected

/tmp/ipykernel_19369/993084553.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['NAMA JEJARING']  = (df_selected['NAMA JEJARING'].astype(str).str.replace(r'^(pustu|polindes|poskesdes|posyandu|kec)\s+', '', regex=True, flags=re.IGNORECASE).str.strip().str.upper())
/tmp/ipykernel_19369/993084553.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['NAMA SERVER']    = ('epuskesmas_ng_live_' + df_selected['NAMA KOTA/KAB'].astype(str).str.lower().str.replace(r'\b(kabupaten|kab|kota)\b', '', regex=True).str.replace(r'[^a-z0-9]', '', regex=True))

,ID PELANGGAN,ID JEJARING,NAMA JEJARING,JENIS FASKES,PROVINSI,NAMA KOTA/KAB,NAMA SERVER
26,P2171010101,PU930,LENGKANG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
27,P2171010101,PU931,PULAU SARANG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
28,P2171010101,PU932,MONGKOL,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
29,P2171010101,PU933,PEMPING,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
30,P2171010101,PU934,PULAU LABUN,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
31,P2171010101,PU935,KEPALA JERI,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
32,P2171010101,PU936,KASU 1,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
33,P2171010101,PU937,KASU 2,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
34,P2171010101,PU938,BERTAM,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
35,P2171010101,PU939,PECONG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
36,P2171010101,PU940,PULAU TERONG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
37,P2171010101,PU941,PEKASIH,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
38,P2171010101,PU942,GERANTING,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
39,P2171020201,PU943,BULANG LINTANG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
40,P2171020201,PU944,PULAU AKAR,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
41,P2171020201,PU945,BULANG KEBAM,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
42,P2171020201,PU946,TEMOYONG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
43,P2171020201,PU947,PULAU LABU,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
44,P2171020201,PU949,SETOKOK,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
45,P2171020201,PU948,PULAU AIR,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
46,P2171020201,PU950,SELAT NENEK,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
47,P2171020201,PU951,PANJANG TIMUR,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
48,P2171020201,PU952,JALOH,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
49,P2171020201,PU953,CENGKUI,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
50,P2171020201,PU954,PULAU SERAYA,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
51,P2171020201,PU955,PULAU NIPAH,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
52,P2171030201,PU956,KARAS,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
53,P2171030201,PU958,MUBUT,POLINDES,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
54,P2171030201,PU959,SEI RAYA,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
55,P2171030201,PU960,DAPUR 6,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
56,P2171030201,PU961,SIJANTUNG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
57,P2171030201,PU962,DAPUR 3,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
58,P2171030201,PU963,TANJUNG BANUN,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
59,P2171030201,PU964,KOREK,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
60,P2171030201,PU965,GALANG BARU,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
61,P2171030201,PU966,AIR LINGKA,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
62,P2171030201,PU967,PULAU PANJANG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
63,P2171030201,PU968,PULAU PANJANG,POLINDES,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
64,P2171030201,PU969,PULAU NGUAN,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
65,P2171030201,PU970,SEMBUR,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
66,P2171030201,PU971,AIR SAGA,POSKESDES,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
67,P2171030201,PU972,PETONG,POLINDES,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
68,P2171030201,PU973,PULAU ABANG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
69,P2171030202,PU974,REMPANG CATE,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
70,P2171030202,PU975,KAMPUNG BARU,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
71,P2171030202,PU976,AIR RAJA,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
72,P2171030202,PU977,SUBANG MAS,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
73,P2171030202,PU978,TANJUNG KERTANG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
74,P2171030202,PU979,PASIR PANJANG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
75,P2171030202,PU980,MONGGAK,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
76,P2171030202,PU981,PANTAI MELAYU,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
77,P2171030202,PU982,TANJUNG KELINGKING,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
78,P2171030202,PU983,BELONGKENG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
79,P2171040101,PU984,KAMPUNG BAGAN,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
80,P2171040101,PU985,DURIANGKANG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
81,P2171040101,PU986,PANCUR BARU,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
82,P2171040101,PU987,TANJUNG PIAYU LAUT,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
83,P2171040101,PU988,BIDA AYU,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
84,P2171040101,PU989,MUKA KUNING,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
85,P2171040101,PU990,MANGSANG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
86,P2171050201,PU991,TELUK MATA IKAN,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
87,P2171050202,PU992,SEI LEKOP,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
88,P2171050202,PU993,SEI BINTI,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
89,P2171050203,PU994,KAVLING SENJULUNG,POSKESDES,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
90,P2171050203,PU995,NGENANG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
91,P2171050203,PU996,KUBUNG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
92,P2171050203,PU997,TELAGA PUNGGUR,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
93,P2171050203,PU998,KAMPUNG PANAU,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
94,P2171050204,PU999,KAMPUNG JABI,POSKESDES,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
95,P2171050204,PU001,BATU BESAR,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
96,P2171050204,PU002,PERMATA BANDARA,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
97,P2171051201,PU001,TAMAN RAYA,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
98,P2171051202,PU001,CIPTA ASRI,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
99,P2171051202,PU002,TEMBESI,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
100,P2171051202,PU003,TG. GUNDAP,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
101,P2171051202,PU004,DAPUR 12,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
102,P2171051202,PU005,DAPUR 12 PANTAI,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
103,P2171060201,PU001,TANJUNG RIAU,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
104,P2171060202,PU001,TIBA LAMA,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
105,P2171060203,PU001,TIBAN INDAH,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
106,P2171060203,PU002,PATAM LESTARI,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
107,P2171061201,PU001,TAMAN LESTARI,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
108,P2171061202,PU001,KP.CUNTING,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
109,P2171061202,PU002,TELUK PANDAN,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
110,P2171070201,PU001,TANJUNG UMA,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
111,P2171070202,PU001,SUNGAI PANAS,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
112,P2171070202,PU002,TAMAN BALOI,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
113,P2171081101,PU001,BENGKONG INDAH,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
114,P2171081102,PU001,TANJUNG BUNTUNG,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
115,P2171081102,PU002,BENGKONG LAUT,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam
116,P2171080201,PU001,TENGKI SERIBU,PUSTU,Kepulauan Riau,Kota Batam,epuskesmas_ng_live_batam

In [28]:
df_to_append = pd.DataFrame({
    "Puskesmas ID": df_selected["ID PELANGGAN"],
    "Code": df_selected["ID PELANGGAN"] + df_selected["ID JEJARING"],
    "Nama Jejaring": df_selected["NAMA JEJARING"],
    "Jenis Jejaring": df_selected["JENIS FASKES"],
    "db_dinkes": df_selected["NAMA SERVER"],
    "PIC_TS": PIC,
    "Created At": CREATED_AT
})

display(df_to_append)

# cross check value to data frame list
# values = df_to_append.values.tolist()
# values

,Puskesmas ID,Code,Nama Jejaring,Jenis Jejaring,db_dinkes,PIC_TS,Created At
11,P7318010101,P7318010101PU001,POTON,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
12,P7318010101,P7318010101PU002,NUSA,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
13,P7318010101,P7318010101PU003,SALUBARANA,POLINDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
14,P7318010101,P7318010101PU004,BAU,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
15,P7318010101,P7318010101PU005,PEAUN,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
16,P7318010101,P7318010101PU006,MAPPA,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
17,P7318051102,P7318051102PU001,SATANDUNG,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
18,P7318051102,P7318051102PU002,SALUTANDUNG,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
19,P7318051102,P7318051102PU003,SALU,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
20,P7318051102,P7318051102PU004,SALU BORONAN,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
21,P7318051102,P7318051102PU005,BATU TIAKKA,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
22,P7318021102,P7318021102PU001,PERINDINGAN,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
23,P7318021102,P7318021102PU002,GANDANGBATU,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
24,P7318021102,P7318021102PU003,GARASSIK,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54
25,P7318021102,P7318021102PU004,KADUAJA,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-26 15:19:54

In [29]:
SPREADSHEET_KONFIGURASI_TS  = '1IAR5thTwLHs42eJ28sqJMPbslhHIm8HnJqH7iTVhDmc'
SHEET_NAME_TARGET           = "Jejaring"

# Get the number of filled rows in the sheet
sheet_metadata = service.spreadsheets().get(spreadsheetId=SPREADSHEET_KONFIGURASI_TS).execute()
sheet_props = next(
    (s for s in sheet_metadata.get("sheets", []) if s["properties"]["title"] == SHEET_NAME_TARGET),
    None
)

if sheet_props:
    grid_props = sheet_props["properties"]["gridProperties"]
    read_range = f"{SHEET_NAME_TARGET}!A:A"
    result = service.spreadsheets().values().get(
        spreadsheetId=SPREADSHEET_KONFIGURASI_TS, range=read_range
    ).execute()
    existing_rows = len(result.get("values", []))
else:
    raise Exception(f"Sheet '{SHEET_NAME_TARGET}' tidak ditemukan.")

# Specify the starting line for appending
start_row = existing_rows + 1
range_append = f"{SHEET_NAME_TARGET}!A{start_row}"
end_row = start_row + len(df_selected) - 1
values = df_to_append.values.tolist()
# Append data
service.spreadsheets().values().append(
    spreadsheetId=SPREADSHEET_KONFIGURASI_TS,
    range=range_append,
    valueInputOption="RAW",
    insertDataOption="INSERT_ROWS",
    body={"values": values}
).execute()

print(f"{len(values)} row successfully added starting from row {start_row} until {end_row}.")

15 row successfully added starting from row 29 until 43.

🔴CONNECT DATABASE🔴

In [33]:
# Configure db
username = "root"
password = "root"           
host     = "localhost"
database = "dummy_data"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}/{database}")

# Check connection
with engine.connect() as conn:
    print("Connected!")

Connected!

🔴CEK JEJARING DI SERVER🔴

In [ ]:
def generate_select_lookup(row):
    id = 'P7318010101'  # id yang ingin dicek

    query = (
        f"SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, "
        f"created_at, updated_at FROM m_puskesmas WHERE id = '{id}'"
    )
    return query

# Tidak perlu loop, cukup 1 query
final_query = generate_select_lookup(None)
# print(final_query)

try:
    df_result = pd.read_sql(final_query, con=engine)
    print("\nHASIL QUERY:")
    # print(df_result)
    
    if df_result.empty:
        print("⚠️ ID TIDAK ADA DI DATABASE")
    else:
        print("✅ ID TERDAFTAR DI DATABASE")

except Exception as e:
    print("Error:", e)

HASIL QUERY:
✅ ID TERDAFTAR DI DATABASE

🔴GET DATA SERVER🔴

In [30]:
# Get faskes id unique for server
id_faskes = df_selected["ID PELANGGAN"].unique()

# Use URL ID
spreadsheet_server  = '15IMGFofJTm9o1r-yiDRh5i9tC8M4G1qH89szm0cCEUM'
sheet               = gc.open_by_key(spreadsheet_server)
worksheet           = sheet.worksheet("Server ePuskesmas")
data_server         = worksheet.get_all_values()

df_sheet_server = pd.DataFrame(data_server[1:], columns=data_server[0])
df_server       = pd.DataFrame()

for server_faskes in id_faskes:
    df_filtered = df_sheet_server[df_sheet_server["puskesmas_id"] == server_faskes]
    df_server   = pd.concat([df_server, df_filtered], ignore_index=True)

    # print(f"Hasil untuk {server_faskes}:")
    # print(df_filtered)

df_server

,puskesmas_id,nama_faskes,Database,server,host
0,P7318010101,BUAKAYU,epuskesmas_ng_live_tanatoraja_P7318010101,sulawesi-selatan-73,10.0.131.208
1,P7318051102,ULUSALU,epuskesmas_ng_live_tanatoraja_P7318051102,sulawesi-selatan-73,10.0.131.208
2,P7318021102,BUNTU,epuskesmas_ng_live_tanatoraja_P7318021102,sulawesi-selatan-73,10.0.131.208

🔴CONNECT DATABASE🔴

In [31]:
# Configure db
username = "root"
password = "root"           
host     = "localhost"
database = "dummy_data"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}/{database}")

# Check connection
with engine.connect() as conn:
    print("Connected!")

Connected!

In [32]:
def generate_select_lookup(row):
    # id             = row['ID PELANGGAN']
    id             = str('P7318010101')


    query = (
        f"SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = {id}"
    )
    return query

queries     = [generate_select_lookup(row) for _, row in df_to_append.iterrows()]
final_query = " UNION ALL\n".join(queries) + ";"
print(final_query)

try:
    df_result = pd.read_sql(final_query, con=engine)
    print("\nHASIL QUERY:")
    print(df_result)

except Exception as e:
    print("Error:", e)

SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101;
Error: (pymysql.err.OperationalError) (1054, "Unknown column 'P7318010101' in 'WHERE'")
[SQL: SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101 UNION ALL
SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = P7318010101;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [19]:
df_to_append = pd.DataFrame({
    "ID PELANGGAN": df_selected["ID PELANGGAN"],
    "Code": df_selected["ID PELANGGAN"] + df_selected["ID JEJARING"],
    "Nama Jejaring": df_selected["NAMA JEJARING"],
    "Jenis Jejaring": df_selected["JENIS FASKES"],
    "db_dinkes": df_selected["NAMA SERVER"],
    "PIC_TS": PIC,
    "Created At": CREATED_AT
})

display(df_to_append)

,ID PELANGGAN,Code,Nama Jejaring,Jenis Jejaring,db_dinkes,PIC_TS,Created At
11,P7318010101,P7318010101PU001,POTON,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
12,P7318010101,P7318010101PU002,NUSA,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
13,P7318010101,P7318010101PU003,SALUBARANA,POLINDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
14,P7318010101,P7318010101PU004,BAU,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
15,P7318010101,P7318010101PU005,PEAUN,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
16,P7318010101,P7318010101PU006,MAPPA,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
17,P7318051102,P7318051102PU001,SATANDUNG,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
18,P7318051102,P7318051102PU002,SALUTANDUNG,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
19,P7318051102,P7318051102PU003,SALU,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
20,P7318051102,P7318051102PU004,SALU BORONAN,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
21,P7318051102,P7318051102PU005,BATU TIAKKA,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
22,P7318021102,P7318021102PU001,PERINDINGAN,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
23,P7318021102,P7318021102PU002,GANDANGBATU,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
24,P7318021102,P7318021102PU003,GARASSIK,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00
25,P7318021102,P7318021102PU004,KADUAJA,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-24 12:00:00

In [ ]:
def generate_select_lookup(row):
    # id             = row['ID PELANGGAN']
    id             = str('P7318010101')


    query = (
        f"SELECT id, jenis_puskesmas, nama, db_database, alamat, stok_obat_realtime, created_at, updated_at FROM m_puskesmas WHERE id = {id}"
    )
    return query

queries     = [generate_select_lookup(row) for _, row in df_to_append.iterrows()]
final_query = " UNION ALL\n".join(queries) + ";"
print(final_query)

try:
    df_result = pd.read_sql(final_query, con=engine)
    print("\nHASIL QUERY:")
    print(df_result)

except Exception as e:
    print("Error:", e)

INSERT KE SERVER

In [41]:
from sqlalchemy import text

# Daftar jejaring (input manual)
jejaring_list = [
    {
        "id_induk": "P7318010101",
        "kode": "PU001",
        "jenis": "PUSTU",
        "nama": "GILILANA"
    },
    {
        "id_induk": "P7318010101",
        "kode": "PU002",
        "jenis": "PUSTU",
        "nama": "TANAUGE"
    },
    # tambah jika perlu
]


def generate_manual_query(item):
    id_induk = item["id_induk"]
    code     = f"{id_induk}{item['kode']}"
    jenis    = item["jenis"]
    nama     = item["nama"]

    return (
        f"SELECT '{code}' AS id, '{jenis}' AS jenis_puskesmas, '{nama}' AS nama, "
        f"db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id AS puskesmas_id, "
        f"0 AS warning_text_id, 1 AS stok_obat_realtime "
        f"FROM m_puskesmas WHERE id = '{id_induk}'"
    )


# Build final INSERT ... SELECT
queries = [generate_manual_query(item) for item in jejaring_list]

final_query = (
    "INSERT INTO dummy_data.`m_puskesmas` "
    "(`id`, `jenis_puskesmas`, `nama`, `db_database`, `propinsi_id`, `kota_id`, `kecamatan_id`, `tanggal_tunda`, "
    "`puskesmas_id`, `warning_text_id`, `stok_obat_realtime`)\n"
    + "UNION ALL\n".join(queries)
    + ";"
)

print("QUERY AKHIR:\n")
print(final_query)


# \U0001f525 EKSEKUSI QUERY INSERT
try:
    with engine.begin() as conn:
        conn.execute(text(final_query))
    print("\n\u2714 DATA BERHASIL DIINSERT KE m_puskesmas!")

except Exception as e:
    print("\n\u274c Error eksekusi:", e)

QUERY AKHIR:

INSERT INTO dummy_data.`m_puskesmas` (`id`, `jenis_puskesmas`, `nama`, `db_database`, `propinsi_id`, `kota_id`, `kecamatan_id`, `tanggal_tunda`, `puskesmas_id`, `warning_text_id`, `stok_obat_realtime`)
SELECT 'P7318010101PU001' AS id, 'PUSTU' AS jenis_puskesmas, 'GILILANA' AS nama, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id AS puskesmas_id, 0 AS warning_text_id, 1 AS stok_obat_realtime FROM m_puskesmas WHERE id = 'P7318010101'UNION ALL
SELECT 'P7318010101PU002' AS id, 'PUSTU' AS jenis_puskesmas, 'TANAUGE' AS nama, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id AS puskesmas_id, 0 AS warning_text_id, 1 AS stok_obat_realtime FROM m_puskesmas WHERE id = 'P7318010101';

✔ DATA BERHASIL DIINSERT KE m_puskesmas!

In [22]:
def generate_select_lookup(row):
    db             = row['db_dinkes']
    jenis_jejaring = row['Jenis Jejaring']

    query = (
        f"SELECT count(1), `value` FROM {db}.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = '{jenis_jejaring}' UNION ALL"
    )
    return query

queries     = [generate_select_lookup(row) for _, row in df_to_append.iterrows()]
final_query = " UNION ALL\n".join(queries) + ";"
# print(final_query)

try:
    df_result = pd.read_sql(final_query, con=engine)
    print("\nHASIL QUERY:")
    print(df_result)

except Exception as e:
    print("Error:", e)

Error: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`for` = 'jenis_puskesmas' and `value` = 'PUSTU' UNION ALL UNION ALL\nSELECT co...' at line 1")
[SQL: SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'PUSTU' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'PUSTU' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'POLINDES' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'POSKESDES' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'POSKESDES' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'POSKESDES' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'PUSTU' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'PUSTU' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'PUSTU' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'PUSTU' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'PUSTU' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'PUSTU' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'PUSTU' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'POSKESDES' UNION ALL UNION ALL
SELECT count(1), `value` FROM epuskesmas_ng_live_tanatoraja.m_lookup HERE `for` = 'jenis_puskesmas' and `value` = 'POSKESDES' UNION ALL;]
(Background on this error at: https://sqlalche.me/e/20/f405)

🔴SAVE TO DATAFRAME🔴

In [ ]:
df_to_append = pd.DataFrame({
    "Puskesmas ID": df_selected["ID PELANGGAN"],
    "Code": df_selected["ID PELANGGAN"] + df_selected["ID JEJARING"],
    "Nama Jejaring": df_selected["NAMA JEJARING"],
    "Jenis Jejaring": df_selected["JENIS FASKES"],
    "db_dinkes": df_selected["NAMA SERVER"],
    "PIC_TS": PIC,
    "Created At": CREATED_AT
})

display(df_to_append)

# cross check value to data frame list
# values = df_to_append.values.tolist()
# values

,Puskesmas ID,Code,Nama Jejaring,Jenis Jejaring,db_dinkes,PIC_TS,Created At
11,P7318010101,P7318010101PU001,POTON,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
12,P7318010101,P7318010101PU002,NUSA,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
13,P7318010101,P7318010101PU003,SALUBARANA,POLINDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
14,P7318010101,P7318010101PU004,BAU,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
15,P7318010101,P7318010101PU005,PEAUN,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
16,P7318010101,P7318010101PU006,MAPPA,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
17,P7318051102,P7318051102PU001,SATANDUNG,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
18,P7318051102,P7318051102PU002,SALUTANDUNG,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
19,P7318051102,P7318051102PU003,SALU,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
20,P7318051102,P7318051102PU004,SALU BORONAN,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
21,P7318051102,P7318051102PU005,BATU TIAKKA,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
22,P7318021102,P7318021102PU001,PERINDINGAN,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
23,P7318021102,P7318021102PU002,GANDANGBATU,PUSTU,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
24,P7318021102,P7318021102PU003,GARASSIK,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00
25,P7318021102,P7318021102PU004,KADUAJA,POSKESDES,epuskesmas_ng_live_tanatoraja,ts_iqbal_agus,2025-11-17 12:00:00

# INSERT FASKES DAN DINKES

In [ ]:
SPREADSHEET_KONFIGURASI_TS  = '1IAR5thTwLHs42eJ28sqJMPbslhHIm8HnJqH7iTVhDmc'
SHEET_NAME_TARGET           = "Jejaring"

INSERT DINKES

In [ ]:
def generate_insert_dinkes(row):
    db_dinkes      = row['db_dinkes']
    code           = row['Code']
    jenis_jejaring = row['Jenis Jejaring']
    nama_jejaring  = row['Nama Jejaring']
    puskesmas_id   = row['Puskesmas ID']
    created_at     = row['Created At']
    pic            = row['PIC_TS']

    query = (
        f"SELECT '{code}' AS code, '{jenis_jejaring}' AS jenis_jejaring,'{nama_jejaring}' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '{created_at}' AS created_at, '{created_at}' AS updated_at, '{pic}' AS created_by, '{pic}' AS updated_by FROM m_puskesmas WHERE id = '{puskesmas_id}'"
    )
    return query

queries     = [generate_insert_dinkes(row) for _, row in df_to_append.iterrows()]
final_query = " UNION ALL\n".join(queries) + ";"
print(final_query)

SELECT 'P7318010101PU001' AS code, 'PUSTU' AS jenis_jejaring,'POTON' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318010101' UNION ALL
SELECT 'P7318010101PU002' AS code, 'PUSTU' AS jenis_jejaring,'NUSA' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318010101' UNION ALL
SELECT 'P7318010101PU003' AS code, 'POLINDES' AS jenis_jejaring,'SALUBARANA' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318010101' UNION ALL
SELECT 'P7318010101PU004' AS code, 'POSKESDES' AS jenis_jejaring,'BAU' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318010101' UNION ALL
SELECT 'P7318010101PU005' AS code, 'POSKESDES' AS jenis_jejaring,'PEAUN' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318010101' UNION ALL
SELECT 'P7318010101PU006' AS code, 'POSKESDES' AS jenis_jejaring,'MAPPA' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318010101' UNION ALL
SELECT 'P7318051102PU001' AS code, 'PUSTU' AS jenis_jejaring,'SATANDUNG' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318051102' UNION ALL
SELECT 'P7318051102PU002' AS code, 'PUSTU' AS jenis_jejaring,'SALUTANDUNG' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318051102' UNION ALL
SELECT 'P7318051102PU003' AS code, 'PUSTU' AS jenis_jejaring,'SALU' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318051102' UNION ALL
SELECT 'P7318051102PU004' AS code, 'PUSTU' AS jenis_jejaring,'SALU BORONAN' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318051102' UNION ALL
SELECT 'P7318051102PU005' AS code, 'PUSTU' AS jenis_jejaring,'BATU TIAKKA' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318051102' UNION ALL
SELECT 'P7318021102PU001' AS code, 'PUSTU' AS jenis_jejaring,'PERINDINGAN' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318021102' UNION ALL
SELECT 'P7318021102PU002' AS code, 'PUSTU' AS jenis_jejaring,'GANDANGBATU' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318021102' UNION ALL
SELECT 'P7318021102PU003' AS code, 'POSKESDES' AS jenis_jejaring,'GARASSIK' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318021102' UNION ALL
SELECT 'P7318021102PU004' AS code, 'POSKESDES' AS jenis_jejaring,'KADUAJA' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '2025-11-14 12:00:00' AS created_at, '2025-11-14 12:00:00' AS updated_at, 'ts_iqbal_agus' AS created_by, 'ts_iqbal_agus' AS updated_by FROM m_puskesmas WHERE id = 'P7318021102';

In [ ]:
def generate_insert_dinkes(row):
    db_dinkes      = row['db_dinkes']
    code           = row['Code']
    jenis_jejaring = row['Jenis Jejaring']
    nama_jejaring  = row['Nama Jejaring']
    puskesmas_id   = row['Puskesmas ID']
    created_at     = row['Created At']
    pic            = row['PIC_TS']

    query = (
        f"SELECT '{code}' AS code, '{jenis_jejaring}' AS jenis_jejaring,'{nama_jejaring}' AS nama_jejaring, db_database, propinsi_id, kota_id, kecamatan_id, tanggal_tunda, id, 0 AS WT, 1 AS STOK, '{created_at}' AS created_at, '{created_at}' AS updated_at, '{pic}' AS created_by, '{pic}' AS updated_by FROM m_puskesmas WHERE id = '{puskesmas_id}'"
    )
    return query

queries = [generate_insert_dinkes(row) for _, row in df_to_append.iterrows()]

final_query = " UNION ALL\n".join(queries) + ";"

print(final_query)

In [ ]:
# Get the number of filled rows in the sheet
sheet_metadata = service.spreadsheets().get(spreadsheetId=SPREADSHEET_KONFIGURASI_TS).execute()
sheet_props = next(
    (s for s in sheet_metadata.get("sheets", []) if s["properties"]["title"] == SHEET_NAME_TARGET),
    None
)

if sheet_props:
    grid_props = sheet_props["properties"]["gridProperties"]
    read_range = f"{SHEET_NAME_TARGET}!A:A"
    result = service.spreadsheets().values().get(
        spreadsheetId=SPREADSHEET_KONFIGURASI_TS, range=read_range
    ).execute()
    existing_rows = len(result.get("values", []))
else:
    raise Exception(f"Sheet '{SHEET_NAME_TARGET}' tidak ditemukan.")

# Specify the starting line for appending
start_row = existing_rows + 1
range_append = f"{SHEET_NAME_TARGET}!A{start_row}"
end_row = start_row + len(df_selected) - 1
values = df_to_append.values.tolist()
# Append data
service.spreadsheets().values().append(
    spreadsheetId=SPREADSHEET_KONFIGURASI_TS,
    range=range_append,
    valueInputOption="RAW",
    insertDataOption="INSERT_ROWS",
    body={"values": values}
).execute()

print(f"{len(values)} row successfully added starting from row {start_row} until {end_row}.")

15 row successfully added starting from row 14 until 28.